class StatusCodesMixin:

    SUCCESS_CREATED = 'SUCCESS_CREATED'
    SUCCESS_DUPLICATE_IGNORED = 'SUCCESS_DUPLICATE_IGNORED'
    SUCCESS_UPDATED = 'SUCCESS_UPDATED'
    SUCCESS_DELETED = 'SUCCESS_DELETED'
    ERROR_SERIALIZATION_ERROR = 'ERROR_SERIALIZATION_ERROR'
    ERROR_VALIDATION_ERROR = 'ERROR_VALIDATION_ERROR'
    ERROR_VALIDATION_DATE_IN_FUTURE = 'ERROR_VALIDATION_DATE_IN_FUTURE'
    ERROR_VALIDATION_CLIENT_NOT_FOUND = 'ERROR_VALIDATION_CLIENT_NOT_FOUND'
    ERROR_VALIDATION_IP_NOT_FOUND = 'ERROR_VALIDATION_IP_NOT_FOUND'
    ERROR_VALIDATION_INTERVENTION_NOT_FOUND= 'ERROR_VALIDATION_INTERVENTION_NOT_FOUND'
    ERROR_ACCESS_DENIED = 'ERROR_ACCESS_DENIED'