# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-05 08:26
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeBracket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Label')),
                ('code', models.IntegerField(verbose_name='Code')),
            ],
            options={
                'verbose_name': 'Age Bracket',
                'verbose_name_plural': 'Age Brackets',
            },
        ),
        migrations.CreateModel(
            name='AgeOfSexualPartner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Age Category')),
                ('code', models.IntegerField(verbose_name='Code')),
            ],
            options={
                'verbose_name_plural': 'Age of Sexual Partner ',
            },
        ),
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('user_id', models.IntegerField()),
                ('table', models.CharField(default='', max_length=200)),
                ('row_id', models.IntegerField(blank=True, null=True)),
                ('action', models.CharField(max_length=100)),
                ('search_text', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'verbose_name': 'Audit',
                'verbose_name_plural': 'Audit log',
            },
        ),
        migrations.CreateModel(
            name='BankingPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Banking Place')),
                ('code', models.IntegerField(verbose_name='Code')),
            ],
            options={
                'verbose_name': 'Banking Place',
                'verbose_name_plural': 'Banking Places',
            },
        ),
        migrations.CreateModel(
            name='CategoricalResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Response Name')),
                ('code', models.IntegerField(verbose_name='Response Code')),
            ],
            options={
                'verbose_name': 'Yes|No Response',
                'verbose_name_plural': 'Yes|No Responses',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, null=True, verbose_name='First Name')),
                ('middle_name', models.CharField(max_length=100, null=True, verbose_name='Middle Name')),
                ('last_name', models.CharField(max_length=100, null=True, verbose_name='Last Name')),
                ('date_of_birth', models.DateField(null=True, verbose_name='Date Of Birth')),
                ('is_date_of_birth_estimated', models.NullBooleanField(default=False, verbose_name='Date of Birth Estimated')),
                ('verification_doc_no', models.CharField(max_length=50, null=True, verbose_name='Verification Doc. No.')),
                ('date_of_enrollment', models.DateField(default=datetime.datetime.now, null=True, verbose_name='Date of Enrollment')),
                ('age_at_enrollment', models.IntegerField(default=10, null=True, verbose_name='Age at Enrollment')),
                ('phone_number', models.CharField(max_length=13, null=True, verbose_name='Phone Number(Client)')),
                ('dss_id_number', models.CharField(max_length=50, null=True, verbose_name='DSS ID Number')),
                ('informal_settlement', models.CharField(max_length=250, null=True, verbose_name='Informal Settlement')),
                ('village', models.CharField(max_length=250, null=True, verbose_name='Village')),
                ('landmark', models.CharField(max_length=250, null=True, verbose_name='Land mark near residence')),
                ('dreams_id', models.CharField(max_length=50, null=True, verbose_name='DREAMS ID')),
                ('guardian_name', models.CharField(max_length=250, null=True, verbose_name="Primary care give / Guardian' name")),
                ('relationship_with_guardian', models.CharField(max_length=50, null=True, verbose_name='Relationship with Guardian')),
                ('guardian_phone_number', models.CharField(max_length=13, null=True, verbose_name='Phone Number(Care giver / Guardian)')),
                ('guardian_national_id', models.CharField(max_length=10, null=True, verbose_name='National ID (Care giver / Guardian)')),
                ('odk_enrollment_uuid', models.CharField(blank=True, max_length=50, null=True)),
                ('date_created', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='ClientCashTransferDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_client_recepient', models.BooleanField(default=False, verbose_name='Is the Recipient an AGYW?')),
                ('recipient_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Name of Recipient')),
                ('recipient_relationship_with_client', models.CharField(blank=True, max_length=150, null=True, verbose_name='Recipient Relationship with AGYW')),
                ('mobile_service_provider_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Name of Mobile Service Provider')),
                ('recipient_phone_number', models.CharField(blank=True, max_length=13, null=True, verbose_name='Phone No')),
                ('name_phone_number_registered_to', models.CharField(blank=True, max_length=250, null=True, verbose_name='Name to whom the Phone No. is registered')),
                ('bank_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Bank')),
                ('bank_branch_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Branch')),
                ('bank_account_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Account name')),
                ('bank_account_number', models.CharField(blank=True, max_length=250, null=True, verbose_name='Account number')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('changed_at', models.DateTimeField(auto_now=True, null=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DreamsApp.Client', verbose_name='Dreams Beneficiary\\(AGYW\\)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cash Transfer Detail',
                'verbose_name_plural': 'Cash Transfer Details',
            },
        ),
        migrations.CreateModel(
            name='ClientDrugUseData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_abuse_last_12months_other', models.CharField(blank=True, max_length=50, null=True)),
                ('drug_used_last_12months_other', models.CharField(blank=True, max_length=50, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DreamsApp.Client')),
                ('drug_abuse_last_12months', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.CategoricalResponse')),
            ],
        ),
        migrations.CreateModel(
            name='ClientEducationAndEmploymentData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_school_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Name of school')),
                ('current_class', models.CharField(blank=True, max_length=10, null=True, verbose_name='Class')),
                ('current_school_level_other', models.CharField(blank=True, max_length=20, null=True, verbose_name='Other Education Level')),
                ('current_education_supporter_other', models.CharField(blank=True, max_length=25, null=True, verbose_name='Support towards current education: other')),
                ('reason_not_in_school_other', models.CharField(max_length=50, null=True, verbose_name='Reason for not going to school: other')),
                ('dropout_class', models.CharField(max_length=50, null=True, verbose_name='Drop out class')),
                ('life_wish_other', models.CharField(blank=True, max_length=50, null=True, verbose_name='Wish in life: other')),
                ('current_income_source_other', models.CharField(max_length=30, null=True, verbose_name='Source of income: other')),
                ('banking_place_other', models.CharField(max_length=20, null=True, verbose_name='Other place for savings')),
                ('banking_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.BankingPlace', verbose_name='Where do you keep your savings?')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DreamsApp.Client')),
            ],
        ),
        migrations.CreateModel(
            name='ClientGenderBasedViolenceData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gbv_help_provider_other', models.CharField(max_length=50, null=True, verbose_name='Other source of GBV help')),
                ('preferred_gbv_help_provider_other', models.CharField(blank=True, max_length=50, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DreamsApp.Client')),
                ('economic_threat_ever', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.CategoricalResponse')),
            ],
        ),
        migrations.CreateModel(
            name='ClientHIVTestingData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('care_facility_enrolled', models.CharField(blank=True, max_length=50, null=True)),
                ('reason_not_in_hiv_care_other', models.CharField(blank=True, max_length=50, null=True)),
                ('reason_never_tested_for_hiv_other', models.CharField(blank=True, max_length=50, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DreamsApp.Client')),
                ('enrolled_in_hiv_care', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.CategoricalResponse')),
                ('ever_tested_for_hiv', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.CategoricalResponse')),
                ('knowledge_of_hiv_test_centres', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.CategoricalResponse')),
            ],
        ),
        migrations.CreateModel(
            name='ClientIndividualAndHouseholdData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_of_household_other', models.CharField(blank=True, max_length=50, null=True)),
                ('age_of_household_head', models.IntegerField(blank=True, null=True)),
                ('is_father_alive', models.IntegerField(null=True, verbose_name='Father alive?')),
                ('is_mother_alive', models.IntegerField(null=True, verbose_name='Mother alive?')),
                ('is_parent_chronically_ill', models.IntegerField(null=True, verbose_name='Is any of your parent/guardian chronically ill?')),
                ('main_floor_material_other', models.CharField(blank=True, max_length=50, null=True, verbose_name='Main floor material: other')),
                ('main_roof_material_other', models.CharField(blank=True, max_length=50, null=True, verbose_name='Main roof material: other')),
                ('main_wall_material_other', models.CharField(blank=True, max_length=50, null=True, verbose_name='Main wall material: other')),
                ('source_of_drinking_water_other', models.CharField(blank=True, max_length=50, null=True, verbose_name='Main source of drinking water: other')),
                ('disability_type_other', models.CharField(blank=True, max_length=50, null=True, verbose_name='Other disability type')),
                ('no_of_people_in_household', models.IntegerField(blank=True, null=True, verbose_name='No of people living in your house')),
                ('no_of_females', models.IntegerField(null=True, verbose_name='No of females')),
                ('no_of_males', models.IntegerField(null=True, verbose_name='No of Males')),
                ('no_of_adults', models.IntegerField(null=True, verbose_name='No of adults')),
                ('no_of_children', models.IntegerField(null=True, verbose_name='No of children')),
                ('current_ct_program', models.CharField(max_length=50, null=True, verbose_name='Cash Transfer Programme currently enrolled in')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DreamsApp.Client')),
                ('currently_in_ct_program', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.CategoricalResponse', verbose_name='Currently enrolled in Cash Transfer?')),
            ],
        ),
        migrations.CreateModel(
            name='ClientParticipationInDreams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dreams_program_other', models.CharField(blank=True, max_length=50, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DreamsApp.Client')),
            ],
        ),
        migrations.CreateModel(
            name='ClientReproductiveHealthData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_biological_children', models.IntegerField(blank=True, null=True)),
                ('anc_facility_name', models.CharField(blank=True, max_length=50, null=True)),
                ('known_fp_method_other', models.CharField(blank=True, max_length=50, null=True)),
                ('current_fp_method_other', models.CharField(blank=True, max_length=50, null=True, verbose_name='Other Modern FP method used')),
                ('reason_not_using_fp_other', models.CharField(blank=True, max_length=50, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DreamsApp.Client')),
                ('current_anc_enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.CategoricalResponse')),
            ],
        ),
        migrations.CreateModel(
            name='ClientSexualActivityData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_at_first_sexual_encounter', models.IntegerField(null=True, verbose_name='Age at first sexual encounter')),
                ('sex_partners_in_last_12months', models.IntegerField(null=True, verbose_name='Sexual partners in the last 12 months')),
                ('age_of_last_partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.AgeOfSexualPartner')),
                ('age_of_second_last_partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.AgeOfSexualPartner')),
                ('age_of_third_last_partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.AgeOfSexualPartner')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DreamsApp.Client')),
                ('ever_had_sex', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.CategoricalResponse')),
                ('has_sexual_partner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.CategoricalResponse')),
                ('know_last_partner_hiv_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.CategoricalResponse')),
                ('know_second_last_partner_hiv_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.CategoricalResponse')),
                ('know_third_last_partner_hiv_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.CategoricalResponse')),
                ('last_partner_circumcised', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.CategoricalResponse')),
                ('received_money_gift_for_sex', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.CategoricalResponse')),
                ('second_last_partner_circumcised', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.CategoricalResponse')),
                ('third_last_partner_circumcised', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.CategoricalResponse')),
            ],
        ),
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=10, verbose_name='County Code')),
                ('name', models.CharField(default='', max_length=100, verbose_name='County')),
            ],
            options={
                'verbose_name': 'County',
                'verbose_name_plural': 'Counties',
            },
        ),
        migrations.CreateModel(
            name='DisabilityType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name of Disability')),
                ('code', models.IntegerField(verbose_name='Disability Code')),
            ],
            options={
                'verbose_name': 'Disability Type',
                'verbose_name_plural': 'Disability Types',
            },
        ),
        migrations.CreateModel(
            name='DreamsProgramme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name of Programme')),
                ('code', models.IntegerField(verbose_name='Code')),
            ],
            options={
                'verbose_name': 'Dreams Programme',
                'verbose_name_plural': 'Dreams Programmes',
            },
        ),
        migrations.CreateModel(
            name='DrinkingWater',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Water Source')),
                ('code', models.IntegerField(verbose_name='Source Code')),
            ],
            options={
                'verbose_name': 'Drinking Water Source',
                'verbose_name_plural': 'Drinking water Sources',
            },
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Drug Abuse/Addiction')),
                ('code', models.IntegerField(verbose_name='Code')),
            ],
            options={
                'verbose_name_plural': 'Drugs',
            },
        ),
        migrations.CreateModel(
            name='EducationSupporter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('code', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Source of Education Support',
                'verbose_name_plural': 'Sources of Education Support',
            },
        ),
        migrations.CreateModel(
            name='FamilyPlanningMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Method')),
                ('code', models.IntegerField(verbose_name='Code')),
            ],
            options={
                'verbose_name': 'Family Planning method',
                'verbose_name_plural': 'Family Planning methods',
            },
        ),
        migrations.CreateModel(
            name='FloorMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Material Name')),
                ('code', models.IntegerField(verbose_name='Material Code')),
            ],
            options={
                'verbose_name': 'Main Floor Material',
                'verbose_name_plural': 'Main Floor Materials',
            },
        ),
        migrations.CreateModel(
            name='FrequencyResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Frequency')),
                ('code', models.IntegerField(verbose_name='Code')),
            ],
            options={
                'verbose_name': 'Frequency Response',
                'verbose_name_plural': 'Frequency Responses',
            },
        ),
        migrations.CreateModel(
            name='GBVHelpProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Source of Support')),
                ('code', models.IntegerField(verbose_name='Code')),
            ],
            options={
                'verbose_name': 'Source of GBV Support',
                'verbose_name_plural': 'Sources of GBV Support',
            },
        ),
        migrations.CreateModel(
            name='Grievance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Date Reported')),
                ('reporter_name', models.CharField(max_length=250, verbose_name='Reporter Name')),
                ('dreams_id', models.CharField(blank=True, max_length=150, null=True, verbose_name='DREAMS ID')),
                ('relationship', models.CharField(blank=True, max_length=50, null=True, verbose_name='Relationship')),
                ('other_specify', models.CharField(blank=True, max_length=150, null=True, verbose_name='Specify')),
                ('reporter_phone', models.CharField(blank=True, max_length=13, null=True, verbose_name='Complainant\u2019s Telephone No')),
                ('received_by', models.CharField(max_length=250, verbose_name='Name of DREAMS staff receiving the grievance')),
                ('receiver_designation', models.CharField(blank=True, max_length=50, null=True, verbose_name='Designation')),
                ('other_grievance_specify', models.CharField(blank=True, max_length=250, null=True, verbose_name='Specify Grievance')),
                ('is_first_time_complaint', models.BooleanField(default=False, verbose_name='Is a 1st Time Complaint')),
                ('person_responsible', models.CharField(blank=True, max_length=250, null=True, verbose_name='Person Responsible')),
                ('resolution', models.TextField(blank=True, null=True, verbose_name='Resolution')),
                ('resolution_date', models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Date of resolution')),
                ('complainant_feedback_date', models.DateField(blank=True, null=True, verbose_name='Date of Feedback to Complainant')),
                ('closed_by', models.CharField(blank=True, max_length=250, null=True, verbose_name='Closed by')),
                ('closure_date', models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Date Closed')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('changed_at', models.DateTimeField(auto_now=True, null=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='county', to='DreamsApp.County', verbose_name='County')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'verbose_name': 'Grievance',
                'verbose_name_plural': 'Grievances',
            },
        ),
        migrations.CreateModel(
            name='GrievanceNature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(verbose_name='Code')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('is_other_specify', models.BooleanField(default=False, verbose_name='Other Specify')),
            ],
            options={
                'verbose_name': 'Nature of Grievance',
                'verbose_name_plural': 'Grievance Nature List',
            },
        ),
        migrations.CreateModel(
            name='GrievanceReporterCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(verbose_name='Code')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('requires_dreams_id', models.BooleanField(default=False, verbose_name='Requires DREAMS ID')),
                ('requires_relationship', models.BooleanField(default=False, verbose_name='Requires Relationship Specification')),
                ('is_other_specified', models.BooleanField(default=False, verbose_name='Other Specify')),
            ],
            options={
                'verbose_name': 'Grievance Reporter Category',
                'verbose_name_plural': 'Grievance Reporter Categories',
            },
        ),
        migrations.CreateModel(
            name='GrievanceStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(verbose_name='Code')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Grievance Status',
                'verbose_name_plural': 'Grievance Status List',
            },
        ),
        migrations.CreateModel(
            name='HivTestResultResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Response')),
                ('code', models.IntegerField(verbose_name='Code')),
            ],
            options={
                'verbose_name': 'HIV Test Response',
                'verbose_name_plural': 'HIV Test Responses',
            },
        ),
        migrations.CreateModel(
            name='HomeVisitVerification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(blank=True, max_length=50, null=True)),
                ('dreams_id', models.CharField(max_length=50, null=True, verbose_name='DREAMS ID')),
                ('village', models.CharField(max_length=50, null=True, verbose_name='Village')),
                ('physical_address', models.CharField(blank=True, max_length=50, null=True)),
                ('visit_date', models.DateField(null=True, verbose_name='Date of visit')),
                ('staff_name', models.CharField(max_length=50, null=True)),
                ('source_of_livelihood_other', models.CharField(blank=True, max_length=50, null=True)),
                ('main_floor_material_other', models.CharField(blank=True, max_length=50, null=True, verbose_name='Main floor material: other')),
                ('main_roof_material_other', models.CharField(blank=True, max_length=50, null=True, verbose_name='Main roof material: other')),
                ('main_wall_material_household_other', models.CharField(blank=True, max_length=50, null=True, verbose_name='Main wall material of the household: other')),
                ('main_wall_material_house_other', models.CharField(blank=True, max_length=50, null=True, verbose_name='Main wall material of your house: other')),
                ('source_of_drinking_water_other', models.CharField(blank=True, max_length=50, null=True, verbose_name='Main source of drinking water: other')),
                ('preferred_beneficiary_name', models.CharField(blank=True, max_length=50, null=True)),
                ('preferred_beneficiary_relationship', models.CharField(blank=True, max_length=50, null=True)),
                ('preferred_beneficiary_id_no', models.CharField(blank=True, max_length=20, null=True)),
                ('household_description', models.CharField(blank=True, max_length=250, null=True)),
                ('age_of_household_head', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DreamsApp.AgeBracket')),
                ('caretaker_illness', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DreamsApp.CategoricalResponse')),
            ],
        ),
        migrations.CreateModel(
            name='HouseholdHead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.IntegerField(verbose_name='Household Head Code')),
            ],
            options={
                'verbose_name': 'Head of Household Category',
                'verbose_name_plural': 'Head of Household Categories',
            },
        ),
        migrations.CreateModel(
            name='HTSResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(verbose_name='HTS Result Code')),
                ('name', models.CharField(max_length=20, verbose_name='HTS Result Name')),
            ],
            options={
                'verbose_name': 'HTS Result',
                'verbose_name_plural': 'HTS Results',
            },
        ),
        migrations.CreateModel(
            name='ImplementingPartner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(verbose_name='Implementing Partner Code')),
                ('name', models.CharField(max_length=150, verbose_name='Implementing Partner Name')),
            ],
            options={
                'verbose_name': 'Implementing Partner',
                'verbose_name_plural': 'Implementing Partners',
            },
        ),
        migrations.CreateModel(
            name='ImplementingPartnerUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('implementing_partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DreamsApp.ImplementingPartner')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Implementing Partner User',
                'verbose_name_plural': 'Implementing Partner Users',
            },
        ),
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intervention_date', models.DateField()),
                ('name_specified', models.CharField(blank=True, max_length=250, null=True)),
                ('client_ccc_number', models.CharField(blank=True, max_length=11, null=True)),
                ('date_linked_to_ccc', models.DateField(blank=True, null=True)),
                ('no_of_sessions_attended', models.IntegerField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, max_length=256, null=True)),
                ('date_created', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('date_changed', models.DateTimeField(blank=True, null=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changed_by', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DreamsApp.Client')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL)),
                ('hts_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DreamsApp.HTSResult')),
                ('implementing_partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='implementing_partner', to='DreamsApp.ImplementingPartner')),
            ],
            options={
                'verbose_name': 'Intervention',
                'verbose_name_plural': 'Interventions',
            },
        ),
        migrations.CreateModel(
            name='InterventionCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(default=0, verbose_name='Intervention Category Code')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Intervention Category',
                'verbose_name_plural': 'Intervention Categories',
            },
        ),
        migrations.CreateModel(
            name='InterventionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(default=0, verbose_name='Intervention Type Code')),
                ('name', models.CharField(max_length=100)),
                ('has_hts_result', models.BooleanField(default=False, verbose_name='Intervention collects HTS Result')),
                ('has_pregnancy_result', models.BooleanField(default=False, verbose_name='Intervention collects Pregnancy Result')),
                ('has_ccc_number', models.BooleanField(default=False, verbose_name='Intervention collects CCC details')),
                ('has_no_of_sessions', models.BooleanField(default=False, verbose_name='Intervention collects No. of sessions')),
                ('min_age', models.IntegerField(default=0, verbose_name='Minimum AGYW Age')),
                ('max_age', models.IntegerField(default=0, verbose_name='Maximum AGYW Age')),
                ('is_age_restricted', models.BooleanField(default=False, verbose_name='Intervention is Age Restricted')),
                ('is_given_once', models.BooleanField(default=False, verbose_name='Intervention is given Once')),
                ('is_specified', models.BooleanField(default=False, verbose_name='Intervention is specified')),
                ('intervention_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DreamsApp.InterventionCategory')),
            ],
            options={
                'verbose_name': 'Intervention Type',
                'verbose_name_plural': 'Intervention Types',
            },
        ),
        migrations.CreateModel(
            name='LifeWish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Wish')),
                ('code', models.IntegerField(verbose_name='Wish Code')),
            ],
            options={
                'verbose_name': 'Life Wish',
                'verbose_name_plural': 'Life Wishes',
            },
        ),
        migrations.CreateModel(
            name='MaritalStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='Marital Status Code')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Marital Status',
                'verbose_name_plural': 'Marital Status',
            },
        ),
        migrations.CreateModel(
            name='PaymentMode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(verbose_name='Code')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Payment Mode',
                'verbose_name_plural': 'Payment Modes',
            },
        ),
        migrations.CreateModel(
            name='PeriodResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Response Name')),
                ('code', models.IntegerField(verbose_name='Response Code')),
            ],
            options={
                'verbose_name': 'Duration Response',
                'verbose_name_plural': 'Duration Responses',
            },
        ),
        migrations.CreateModel(
            name='PregnancyTestResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(verbose_name='Pregnancy Result Code')),
                ('name', models.CharField(max_length=20, verbose_name='Pregnancy Result Name')),
            ],
            options={
                'verbose_name': 'Pregnancy Result',
                'verbose_name_plural': 'Pregnancy Results',
            },
        ),
        migrations.CreateModel(
            name='ReasonNotInHIVCare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Response')),
                ('code', models.IntegerField(verbose_name='Code')),
            ],
            options={
                'verbose_name': 'Reason not in HIV Care',
                'verbose_name_plural': 'Reasons not in HIV Care',
            },
        ),
        migrations.CreateModel(
            name='ReasonNotInSchool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Reason')),
                ('code', models.IntegerField(verbose_name='Reason Code')),
            ],
            options={
                'verbose_name': 'Reason not in School',
                'verbose_name_plural': 'Reasons not in School',
            },
        ),
        migrations.CreateModel(
            name='ReasonNotTestedForHIV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Response')),
                ('code', models.IntegerField(verbose_name='Code')),
            ],
            options={
                'verbose_name': 'Reason not tested for HIV',
                'verbose_name_plural': 'Reasons not tested for HIV ',
            },
        ),
        migrations.CreateModel(
            name='ReasonNotUsingFamilyPlanning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Reason')),
                ('code', models.IntegerField(verbose_name='Code')),
            ],
            options={
                'verbose_name': 'Reason not using Family Planning',
                'verbose_name_plural': 'Reasons not using Family Planning',
            },
        ),
        migrations.CreateModel(
            name='RoofingMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Material Name')),
                ('code', models.IntegerField(verbose_name='Material Code')),
            ],
            options={
                'verbose_name': 'Main Roofing Material',
                'verbose_name_plural': 'Main Roofing Materials',
            },
        ),
        migrations.CreateModel(
            name='SchoolLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Education Level Name')),
                ('code', models.IntegerField(verbose_name='Education Level Code')),
            ],
            options={
                'verbose_name': 'Level of Education',
                'verbose_name_plural': 'Levels of Education',
            },
        ),
        migrations.CreateModel(
            name='SchoolType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.IntegerField(verbose_name='Type Code')),
            ],
            options={
                'verbose_name': 'School Type',
                'verbose_name_plural': 'School Types',
            },
        ),
        migrations.CreateModel(
            name='SourceOfIncome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Source')),
                ('code', models.IntegerField(verbose_name='Code')),
            ],
            options={
                'verbose_name': 'Source of Income',
                'verbose_name_plural': 'Sources of Income',
            },
        ),
        migrations.CreateModel(
            name='SubCounty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=100, verbose_name='Sub County Code')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Sub County')),
                ('county', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DreamsApp.County')),
            ],
            options={
                'verbose_name': 'Sub County',
                'verbose_name_plural': 'Sub Counties',
            },
        ),
        migrations.CreateModel(
            name='VerificationDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(verbose_name='Verification Document Code')),
                ('name', models.CharField(max_length=150, verbose_name='Verification Document Name')),
            ],
            options={
                'verbose_name': 'Verification Document',
                'verbose_name_plural': 'Verification Documents',
            },
        ),
        migrations.CreateModel(
            name='WallMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Material Name')),
                ('code', models.IntegerField(verbose_name='Material Code')),
            ],
            options={
                'verbose_name': 'Main Wall Material',
                'verbose_name_plural': 'Main Wall Materials',
            },
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=100, verbose_name='Ward Code')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Ward')),
                ('sub_county', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DreamsApp.SubCounty')),
            ],
            options={
                'verbose_name': 'Ward',
                'verbose_name_plural': 'Wards',
            },
        ),
        migrations.AddField(
            model_name='intervention',
            name='intervention_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DreamsApp.InterventionType'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='pregnancy_test_result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DreamsApp.PregnancyTestResult'),
        ),
        migrations.AddField(
            model_name='homevisitverification',
            name='implementing_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DreamsApp.ImplementingPartner'),
        ),
        migrations.AddField(
            model_name='homevisitverification',
            name='main_floor_material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.FloorMaterial', verbose_name='Main floor material'),
        ),
        migrations.AddField(
            model_name='homevisitverification',
            name='main_roof_material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.RoofingMaterial', verbose_name='Main roof material'),
        ),
        migrations.AddField(
            model_name='homevisitverification',
            name='main_wall_material_house',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.WallMaterial', verbose_name='Main wall material of your housse'),
        ),
        migrations.AddField(
            model_name='homevisitverification',
            name='main_wall_material_household',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.WallMaterial', verbose_name='Main wall material of the household'),
        ),
        migrations.AddField(
            model_name='homevisitverification',
            name='no_of_days_missed_food_in_4wks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.FrequencyResponse'),
        ),
        migrations.AddField(
            model_name='homevisitverification',
            name='source_of_drinking_water',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.DrinkingWater', verbose_name='Main source of drinking water'),
        ),
        migrations.AddField(
            model_name='homevisitverification',
            name='source_of_livelihood',
            field=models.ManyToManyField(to='DreamsApp.SourceOfIncome'),
        ),
        migrations.AddField(
            model_name='homevisitverification',
            name='ward',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DreamsApp.Ward', verbose_name='Ward'),
        ),
        migrations.AddField(
            model_name='grievance',
            name='grievance_nature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grievance_nature', to='DreamsApp.GrievanceNature', verbose_name='Nature of Grievance'),
        ),
        migrations.AddField(
            model_name='grievance',
            name='implementing_partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DreamsApp.ImplementingPartner', verbose_name='Implementing Partner'),
        ),
        migrations.AddField(
            model_name='grievance',
            name='reporter_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporter_category', to='DreamsApp.GrievanceReporterCategory', verbose_name='Reporter Category'),
        ),
        migrations.AddField(
            model_name='grievance',
            name='status',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='DreamsApp.GrievanceStatus', verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='grievance',
            name='ward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ward', to='DreamsApp.Ward', verbose_name='Ward'),
        ),
        migrations.AddField(
            model_name='clientsexualactivitydata',
            name='used_condom_with_last_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.FrequencyResponse'),
        ),
        migrations.AddField(
            model_name='clientsexualactivitydata',
            name='used_condom_with_second_last_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.FrequencyResponse'),
        ),
        migrations.AddField(
            model_name='clientsexualactivitydata',
            name='used_condom_with_third_last_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.FrequencyResponse'),
        ),
        migrations.AddField(
            model_name='clientreproductivehealthdata',
            name='current_fp_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.FamilyPlanningMethod'),
        ),
        migrations.AddField(
            model_name='clientreproductivehealthdata',
            name='currently_pregnant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.CategoricalResponse'),
        ),
        migrations.AddField(
            model_name='clientreproductivehealthdata',
            name='currently_use_modern_fp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.CategoricalResponse'),
        ),
        migrations.AddField(
            model_name='clientreproductivehealthdata',
            name='fp_methods_awareness',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.CategoricalResponse'),
        ),
        migrations.AddField(
            model_name='clientreproductivehealthdata',
            name='has_biological_children',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.CategoricalResponse'),
        ),
        migrations.AddField(
            model_name='clientreproductivehealthdata',
            name='known_fp_method',
            field=models.ManyToManyField(blank=True, related_name='_clientreproductivehealthdata_known_fp_method_+', to='DreamsApp.FamilyPlanningMethod'),
        ),
        migrations.AddField(
            model_name='clientreproductivehealthdata',
            name='reason_not_using_fp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.ReasonNotUsingFamilyPlanning'),
        ),
        migrations.AddField(
            model_name='clientparticipationindreams',
            name='dreams_program',
            field=models.ManyToManyField(blank=True, to='DreamsApp.DreamsProgramme'),
        ),
        migrations.AddField(
            model_name='clientindividualandhouseholddata',
            name='disability_type',
            field=models.ManyToManyField(blank=True, to='DreamsApp.DisabilityType'),
        ),
        migrations.AddField(
            model_name='clientindividualandhouseholddata',
            name='ever_enrolled_in_ct_program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.CategoricalResponse', verbose_name='Ever enrolled in Cash Transfer?'),
        ),
        migrations.AddField(
            model_name='clientindividualandhouseholddata',
            name='ever_missed_full_day_food_in_4wks',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.CategoricalResponse'),
        ),
        migrations.AddField(
            model_name='clientindividualandhouseholddata',
            name='has_disability',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.CategoricalResponse', verbose_name='Disabled?'),
        ),
        migrations.AddField(
            model_name='clientindividualandhouseholddata',
            name='head_of_household',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.HouseholdHead'),
        ),
        migrations.AddField(
            model_name='clientindividualandhouseholddata',
            name='main_floor_material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.FloorMaterial', verbose_name='Main floor material'),
        ),
        migrations.AddField(
            model_name='clientindividualandhouseholddata',
            name='main_roof_material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.RoofingMaterial', verbose_name='Main roof material'),
        ),
        migrations.AddField(
            model_name='clientindividualandhouseholddata',
            name='main_wall_material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.WallMaterial', verbose_name='Main wall material'),
        ),
        migrations.AddField(
            model_name='clientindividualandhouseholddata',
            name='no_of_days_missed_food_in_4wks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.FrequencyResponse'),
        ),
        migrations.AddField(
            model_name='clientindividualandhouseholddata',
            name='source_of_drinking_water',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.DrinkingWater', verbose_name='Main source of drinking water'),
        ),
        migrations.AddField(
            model_name='clienthivtestingdata',
            name='last_test_result',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.HivTestResultResponse'),
        ),
        migrations.AddField(
            model_name='clienthivtestingdata',
            name='period_last_tested',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.PeriodResponse'),
        ),
        migrations.AddField(
            model_name='clienthivtestingdata',
            name='reason_never_tested_for_hiv',
            field=models.ManyToManyField(blank=True, to='DreamsApp.ReasonNotTestedForHIV'),
        ),
        migrations.AddField(
            model_name='clienthivtestingdata',
            name='reason_not_in_hiv_care',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.ReasonNotInHIVCare'),
        ),
        migrations.AddField(
            model_name='clientgenderbasedviolencedata',
            name='economic_threat_last_3months',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.FrequencyResponse'),
        ),
        migrations.AddField(
            model_name='clientgenderbasedviolencedata',
            name='gbv_help_provider',
            field=models.ManyToManyField(blank=True, related_name='_clientgenderbasedviolencedata_gbv_help_provider_+', to='DreamsApp.GBVHelpProvider'),
        ),
        migrations.AddField(
            model_name='clientgenderbasedviolencedata',
            name='humiliated_ever',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.CategoricalResponse'),
        ),
        migrations.AddField(
            model_name='clientgenderbasedviolencedata',
            name='humiliated_last_3months',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.FrequencyResponse'),
        ),
        migrations.AddField(
            model_name='clientgenderbasedviolencedata',
            name='insulted_ever',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.CategoricalResponse'),
        ),
        migrations.AddField(
            model_name='clientgenderbasedviolencedata',
            name='insulted_last_3months',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.FrequencyResponse'),
        ),
        migrations.AddField(
            model_name='clientgenderbasedviolencedata',
            name='knowledge_of_gbv_help_centres',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.CategoricalResponse'),
        ),
        migrations.AddField(
            model_name='clientgenderbasedviolencedata',
            name='physical_violence_ever',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.CategoricalResponse'),
        ),
        migrations.AddField(
            model_name='clientgenderbasedviolencedata',
            name='physical_violence_last_3months',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.FrequencyResponse'),
        ),
        migrations.AddField(
            model_name='clientgenderbasedviolencedata',
            name='physically_forced_other_sex_acts_ever',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.CategoricalResponse'),
        ),
        migrations.AddField(
            model_name='clientgenderbasedviolencedata',
            name='physically_forced_other_sex_acts_last_3months',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.FrequencyResponse'),
        ),
        migrations.AddField(
            model_name='clientgenderbasedviolencedata',
            name='physically_forced_sex_ever',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.CategoricalResponse'),
        ),
        migrations.AddField(
            model_name='clientgenderbasedviolencedata',
            name='physically_forced_sex_last_3months',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.FrequencyResponse'),
        ),
        migrations.AddField(
            model_name='clientgenderbasedviolencedata',
            name='preferred_gbv_help_provider',
            field=models.ManyToManyField(blank=True, related_name='_clientgenderbasedviolencedata_preferred_gbv_help_provider_+', to='DreamsApp.GBVHelpProvider'),
        ),
        migrations.AddField(
            model_name='clientgenderbasedviolencedata',
            name='seek_help_after_gbv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.CategoricalResponse'),
        ),
        migrations.AddField(
            model_name='clientgenderbasedviolencedata',
            name='threatened_for_sexual_acts_ever',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.CategoricalResponse'),
        ),
        migrations.AddField(
            model_name='clientgenderbasedviolencedata',
            name='threatened_for_sexual_acts_last_3months',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.FrequencyResponse'),
        ),
        migrations.AddField(
            model_name='clientgenderbasedviolencedata',
            name='threats_to_hurt_ever',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.CategoricalResponse'),
        ),
        migrations.AddField(
            model_name='clientgenderbasedviolencedata',
            name='threats_to_hurt_last_3months',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.FrequencyResponse'),
        ),
        migrations.AddField(
            model_name='clienteducationandemploymentdata',
            name='current_education_supporter',
            field=models.ManyToManyField(blank=True, to='DreamsApp.EducationSupporter'),
        ),
        migrations.AddField(
            model_name='clienteducationandemploymentdata',
            name='current_income_source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.SourceOfIncome', verbose_name='Current source of income'),
        ),
        migrations.AddField(
            model_name='clienteducationandemploymentdata',
            name='current_school_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.SchoolLevel', verbose_name='Current school level'),
        ),
        migrations.AddField(
            model_name='clienteducationandemploymentdata',
            name='current_school_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.SchoolType', verbose_name='Type of school'),
        ),
        migrations.AddField(
            model_name='clienteducationandemploymentdata',
            name='currently_in_school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.CategoricalResponse', verbose_name='Currently schooling'),
        ),
        migrations.AddField(
            model_name='clienteducationandemploymentdata',
            name='dropout_school_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.SchoolLevel'),
        ),
        migrations.AddField(
            model_name='clienteducationandemploymentdata',
            name='has_savings',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.CategoricalResponse', verbose_name='Do you have savings?'),
        ),
        migrations.AddField(
            model_name='clienteducationandemploymentdata',
            name='last_time_in_school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.PeriodResponse', verbose_name='Last time in school'),
        ),
        migrations.AddField(
            model_name='clienteducationandemploymentdata',
            name='life_wish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.LifeWish', verbose_name='Wish in life'),
        ),
        migrations.AddField(
            model_name='clienteducationandemploymentdata',
            name='reason_not_in_school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.ReasonNotInSchool', verbose_name='Reason for not going to school'),
        ),
        migrations.AddField(
            model_name='clientdrugusedata',
            name='drug_used_last_12months',
            field=models.ManyToManyField(to='DreamsApp.Drug'),
        ),
        migrations.AddField(
            model_name='clientdrugusedata',
            name='frequency_of_alcohol_last_12months',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DreamsApp.FrequencyResponse'),
        ),
        migrations.AddField(
            model_name='clientdrugusedata',
            name='produced_alcohol_last_12months',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.CategoricalResponse'),
        ),
        migrations.AddField(
            model_name='clientdrugusedata',
            name='used_alcohol_last_12months',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.CategoricalResponse'),
        ),
        migrations.AddField(
            model_name='clientcashtransferdetails',
            name='payment_mode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DreamsApp.PaymentMode', verbose_name='Prefered Mode of receiving Cash'),
        ),
        migrations.AddField(
            model_name='client',
            name='county_of_residence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DreamsApp.County', verbose_name='County of residence'),
        ),
        migrations.AddField(
            model_name='client',
            name='enrolled_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='client',
            name='implementing_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DreamsApp.ImplementingPartner'),
        ),
        migrations.AddField(
            model_name='client',
            name='marital_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DreamsApp.MaritalStatus', verbose_name='Marital Status'),
        ),
        migrations.AddField(
            model_name='client',
            name='sub_county',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DreamsApp.SubCounty', verbose_name='Sub County'),
        ),
        migrations.AddField(
            model_name='client',
            name='verification_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DreamsApp.VerificationDocument'),
        ),
        migrations.AddField(
            model_name='client',
            name='ward',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DreamsApp.Ward', verbose_name='Ward'),
        ),
    ]
