# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-12 07:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HTSResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(verbose_name='HTS Result Code')),
                ('name', models.CharField(max_length=20, verbose_name='HTS Result Name')),
            ],
            options={
                'verbose_name': 'HTS Result',
                'verbose_name_plural': 'HTS Results',
            },
        ),
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intervention_date', models.DateField()),
                ('client_ccc_number', models.CharField(blank=True, max_length=11, null=True)),
                ('date_linked_to_ccc', models.DateField(blank=True, null=True)),
                ('no_of_sessions_attended', models.IntegerField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, max_length=256, null=True)),
            ],
            options={
                'verbose_name': 'Intervention',
                'verbose_name_plural': 'Interventions',
            },
        ),
        migrations.CreateModel(
            name='InterventionCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(default=0, verbose_name='Intervention Category Code')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Intervention Category',
                'verbose_name_plural': 'Intervention Categories',
            },
        ),
        migrations.CreateModel(
            name='InterventionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(default=0, verbose_name='Intervention Type Code')),
                ('name', models.CharField(max_length=30)),
                ('intervention_category',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DreamsApp.InterventionCategory')),
            ],
            options={
                'verbose_name': 'Intervention Type',
                'verbose_name_plural': 'Intervention Types',
            },
        ),
        migrations.CreateModel(
            name='PregnancyTestResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(verbose_name='Pregnancy Result Code')),
                ('name', models.CharField(max_length=20, verbose_name='Pregnancy Result Name')),
            ],
            options={
                'verbose_name': 'Pregnancy Result',
                'verbose_name_plural': 'Pregnancy Results',
            },
        ),
        migrations.CreateModel(
            name='Woman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('date_of_birth', models.DateField(verbose_name='Date Of Birth')),
            ],
            options={
                'verbose_name_plural': 'Women',
            },
        ),
        migrations.AddField(
            model_name='intervention',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DreamsApp.Woman'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='hts_result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='DreamsApp.HTSResult'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='intervention_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='DreamsApp.InterventionType'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='pregnancy_test_result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='DreamsApp.PregnancyTestResult'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
