# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 09:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HIVTestResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(verbose_name='HIV Test Result Code')),
                ('name', models.CharField(max_length=20, verbose_name='HIV Test Result')),
            ],
        ),
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_completed', models.DateField()),
                ('hiv_test_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DreamsApp.HIVTestResult')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InterventionCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.IntegerField(verbose_name='Intervention Category Code')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='InterventionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.IntegerField(verbose_name='Intervention Type Code')),
                ('name', models.CharField(max_length=30)),
                ('intervention_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DreamsApp.InterventionCategory')),
            ],
        ),
        migrations.CreateModel(
            name='Woman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('date_of_birth', models.DateField(verbose_name='Date Of Birth')),
            ],
        ),
        migrations.AddField(
            model_name='intervention',
            name='woman',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DreamsApp.Woman'),
        ),
    ]
