# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 09:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DreamsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervention',
            name='intervention_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DreamsApp.InterventionType'),
        ),
    ]
