# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-10 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DreamsApp', '0002_auto_20161010_0754'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlatEnrollmentTableLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_started', models.DateTimeField(null=True)),
                ('date_completed', models.DateTimeField(null=True)),
                ('activity', models.CharField(max_length=50)),
                ('error', models.CharField(max_length=255)),
            ],
        ),
    ]
