# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-10 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DreamsApp', '0003_flatenrollmenttablelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flatenrollmenttablelog',
            name='error',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
