# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-27 06:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('DreamsApp', '0006_auto_20160427_0520'),
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=10, verbose_name='County Code')),
                ('name', models.CharField(default='', max_length=100, verbose_name='County')),
            ],
            options={
                'verbose_name': 'County',
                'verbose_name_plural': 'Counties',
            },
        ),
        migrations.CreateModel(
            name='MaritalStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(default=0, verbose_name='Marital Status Code')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Marital Status',
                'verbose_name_plural': 'Marital Status',
            },
        ),
        migrations.AddField(
            model_name='client',
            name='aget_at_enrollment',
            field=models.IntegerField(default=10, verbose_name='Age at Enrollment'),
        ),
        migrations.AddField(
            model_name='client',
            name='date_at_enrollment',
            field=models.DateField(null=True, verbose_name='Date at Enrollment'),
        ),
        migrations.AddField(
            model_name='client',
            name='dss_id_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='DSS ID Number'),
        ),
        migrations.AddField(
            model_name='client',
            name='is_date_of_birth_estimated',
            field=models.BooleanField(default=False, verbose_name='Date of Birth Estimated'),
        ),
        migrations.AddField(
            model_name='client',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='Phone Number(Client)'),
        ),
        migrations.AddField(
            model_name='client',
            name='verification_doc_no',
            field=models.CharField(blank=True, default='', max_length=50, null=True,
                                   verbose_name='Verification Doc. No.'),
        ),
        migrations.AlterField(
            model_name='client',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='client',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='client',
            name='middle_name',
            field=models.CharField(max_length=100, verbose_name='Middle Name'),
        ),
        migrations.AddField(
            model_name='client',
            name='county_of_residence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='DreamsApp.County', verbose_name='County of residence'),
        ),
        migrations.AddField(
            model_name='client',
            name='marital_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='DreamsApp.MaritalStatus', verbose_name='Marital Status'),
        ),
    ]
