# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-13 05:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DreamsApp', '0006_auto_20161013_0538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intervention',
            name='date_changed',
        ),
        migrations.RemoveField(
            model_name='intervention',
            name='date_created',
        ),
    ]
