# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-27 06:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('DreamsApp', '0007_auto_20160427_0602'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCounty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=10, verbose_name='Sub County Code')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Sub County')),
                ('county', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                             to='DreamsApp.County')),
            ],
            options={
                'verbose_name': 'Sub County',
                'verbose_name_plural': 'Sub Counties',
            },
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=10, verbose_name='Ward Code')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Ward')),
                ('county', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                             to='DreamsApp.SubCounty')),
            ],
            options={
                'verbose_name': 'Ward',
                'verbose_name_plural': 'Wards',
            },
        ),
        migrations.AddField(
            model_name='client',
            name='sub_county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='DreamsApp.SubCounty', verbose_name='Sub County'),
        ),
        migrations.AddField(
            model_name='client',
            name='ward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='DreamsApp.Ward', verbose_name='Ward'),
        ),
    ]
