# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-13 05:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DreamsApp', '0008_intervention_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervention',
            name='date_changed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
