# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-27 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DreamsApp', '0009_auto_20160427_0621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='aget_at_enrollment',
        ),
        migrations.AddField(
            model_name='client',
            name='age_at_enrollment',
            field=models.IntegerField(blank=True, default=10, null=True, verbose_name='Age at Enrollment'),
        ),
        migrations.AlterField(
            model_name='client',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='client',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='client',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Middle Name'),
        ),
    ]
