# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-27 09:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DreamsApp', '0010_auto_20161013_0555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='county_of_residence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DreamsApp.County', verbose_name='County of Residence'),
        ),
        migrations.AlterField(
            model_name='client',
            name='date_of_birth',
            field=models.DateField(null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='client',
            name='guardian_name',
            field=models.CharField(max_length=250, null=True, verbose_name="Primary Care Giver/Guardian' Name"),
        ),
        migrations.AlterField(
            model_name='client',
            name='guardian_national_id',
            field=models.CharField(max_length=10, null=True, verbose_name='National ID (Care giver/Guardian)'),
        ),
        migrations.AlterField(
            model_name='client',
            name='guardian_phone_number',
            field=models.CharField(max_length=13, null=True, verbose_name='Phone Number(Care giver/Guardian)'),
        ),
        migrations.AlterField(
            model_name='client',
            name='implementing_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DreamsApp.ImplementingPartner', verbose_name='Implementing Partner'),
        ),
        migrations.AlterField(
            model_name='client',
            name='landmark',
            field=models.CharField(max_length=250, null=True, verbose_name='Land Mark near Residence'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(max_length=13, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='client',
            name='verification_doc_no',
            field=models.CharField(max_length=50, null=True, verbose_name='Verification Doc No'),
        ),
        migrations.AlterField(
            model_name='client',
            name='verification_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DreamsApp.VerificationDocument', verbose_name='Verification Document'),
        ),
        migrations.AlterField(
            model_name='clienteducationandemploymentdata',
            name='current_class',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Class/Form'),
        ),
        migrations.AlterField(
            model_name='clienteducationandemploymentdata',
            name='current_education_supporter',
            field=models.ManyToManyField(blank=True, to='DreamsApp.EducationSupporter', verbose_name='Supporter towards current Education'),
        ),
        migrations.AlterField(
            model_name='clienteducationandemploymentdata',
            name='current_education_supporter_other',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Supporter towards current Education(other)'),
        ),
        migrations.AlterField(
            model_name='clienteducationandemploymentdata',
            name='current_income_source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.SourceOfIncome', verbose_name='Current source of Income'),
        ),
        migrations.AlterField(
            model_name='clienteducationandemploymentdata',
            name='current_income_source_other',
            field=models.CharField(max_length=30, null=True, verbose_name='Source of income(other)'),
        ),
        migrations.AlterField(
            model_name='clienteducationandemploymentdata',
            name='current_school_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.SchoolLevel', verbose_name='Current School Level'),
        ),
        migrations.AlterField(
            model_name='clienteducationandemploymentdata',
            name='current_school_level_other',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='School Level(Other)'),
        ),
        migrations.AlterField(
            model_name='clienteducationandemploymentdata',
            name='current_school_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Name of School'),
        ),
        migrations.AlterField(
            model_name='clienteducationandemploymentdata',
            name='current_school_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.SchoolType', verbose_name='Type of School'),
        ),
        migrations.AlterField(
            model_name='clienteducationandemploymentdata',
            name='dropout_class',
            field=models.CharField(max_length=50, null=True, verbose_name='Drop out Class'),
        ),
        migrations.AlterField(
            model_name='clienteducationandemploymentdata',
            name='last_time_in_school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.PeriodResponse', verbose_name='Last time in School'),
        ),
        migrations.AlterField(
            model_name='clienteducationandemploymentdata',
            name='life_wish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.LifeWish', verbose_name='Wish in Life'),
        ),
        migrations.AlterField(
            model_name='clienteducationandemploymentdata',
            name='life_wish_other',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Wish in life(other)'),
        ),
        migrations.AlterField(
            model_name='clienteducationandemploymentdata',
            name='reason_not_in_school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.ReasonNotInSchool', verbose_name='Reason for not going to School'),
        ),
        migrations.AlterField(
            model_name='clienteducationandemploymentdata',
            name='reason_not_in_school_other',
            field=models.CharField(max_length=50, null=True, verbose_name='Reason for not going to school(other)'),
        ),
        migrations.AlterField(
            model_name='clienthivtestingdata',
            name='care_facility_enrolled',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Name of Facility'),
        ),
        migrations.AlterField(
            model_name='clienthivtestingdata',
            name='enrolled_in_hiv_care',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.CategoricalResponse', verbose_name='Enrolled in HIV Care?'),
        ),
        migrations.AlterField(
            model_name='clienthivtestingdata',
            name='ever_tested_for_hiv',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.CategoricalResponse', verbose_name='Ever Tested for HIV'),
        ),
        migrations.AlterField(
            model_name='clienthivtestingdata',
            name='knowledge_of_hiv_test_centres',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.CategoricalResponse', verbose_name='Know places where people get tested for HIV?'),
        ),
        migrations.AlterField(
            model_name='clienthivtestingdata',
            name='last_test_result',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.HivTestResultResponse', verbose_name='Last Test Result'),
        ),
        migrations.AlterField(
            model_name='clienthivtestingdata',
            name='period_last_tested',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.PeriodResponse', verbose_name='Period last Tested'),
        ),
        migrations.AlterField(
            model_name='clienthivtestingdata',
            name='reason_never_tested_for_hiv',
            field=models.ManyToManyField(blank=True, to='DreamsApp.ReasonNotTestedForHIV', verbose_name='Reason never tested for HIV'),
        ),
        migrations.AlterField(
            model_name='clienthivtestingdata',
            name='reason_never_tested_for_hiv_other',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Reason never tested for HIV(Other)'),
        ),
        migrations.AlterField(
            model_name='clienthivtestingdata',
            name='reason_not_in_hiv_care',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.ReasonNotInHIVCare', verbose_name='Reason not in Care'),
        ),
        migrations.AlterField(
            model_name='clienthivtestingdata',
            name='reason_not_in_hiv_care_other',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Reason not in HIV Care(Other)'),
        ),
        migrations.AlterField(
            model_name='clientindividualandhouseholddata',
            name='current_ct_program',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Cash Transfer Programme currently enrolled in'),
        ),
        migrations.AlterField(
            model_name='clientindividualandhouseholddata',
            name='is_father_alive',
            field=models.ForeignKey(db_column='is_father_alive', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.CategoricalResponse', verbose_name='Father alive?'),
        ),
        migrations.AlterField(
            model_name='clientindividualandhouseholddata',
            name='is_mother_alive',
            field=models.ForeignKey(db_column='is_mother_alive', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.CategoricalResponse', verbose_name='Mother alive?'),
        ),
        migrations.AlterField(
            model_name='clientindividualandhouseholddata',
            name='is_parent_chronically_ill',
            field=models.ForeignKey(db_column='is_parent_chronically_ill', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.CategoricalResponse', verbose_name='Is any of your parent/guardian chronically ill?'),
        ),
        migrations.AlterField(
            model_name='clientreproductivehealthdata',
            name='anc_facility_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Which clinic/facility are you currently seeking ANC services'),
        ),
        migrations.AlterField(
            model_name='clientreproductivehealthdata',
            name='current_anc_enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.CategoricalResponse', verbose_name='Are you attending ANC Clinic for this pregnancy'),
        ),
        migrations.AlterField(
            model_name='clientreproductivehealthdata',
            name='current_fp_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.FamilyPlanningMethod', verbose_name='Which family planning method are you currently using?'),
        ),
        migrations.AlterField(
            model_name='clientreproductivehealthdata',
            name='currently_pregnant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.CategoricalResponse', verbose_name='Are you currently pregnant?'),
        ),
        migrations.AlterField(
            model_name='clientreproductivehealthdata',
            name='currently_use_modern_fp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.CategoricalResponse', verbose_name='Are you currently using any modern family planning method?'),
        ),
        migrations.AlterField(
            model_name='clientreproductivehealthdata',
            name='fp_methods_awareness',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.CategoricalResponse', verbose_name='Are you aware of any family planning methods?'),
        ),
        migrations.AlterField(
            model_name='clientreproductivehealthdata',
            name='has_biological_children',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.CategoricalResponse', verbose_name='Do you have biological children?'),
        ),
        migrations.AlterField(
            model_name='clientreproductivehealthdata',
            name='known_fp_method',
            field=models.ManyToManyField(blank=True, related_name='_clientreproductivehealthdata_known_fp_method_+', to='DreamsApp.FamilyPlanningMethod', verbose_name='Which family planning methods do you know of?'),
        ),
        migrations.AlterField(
            model_name='clientreproductivehealthdata',
            name='known_fp_method_other',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Family planning method(Other)'),
        ),
        migrations.AlterField(
            model_name='clientreproductivehealthdata',
            name='no_of_biological_children',
            field=models.IntegerField(blank=True, null=True, verbose_name='How many biological children do you have?'),
        ),
        migrations.AlterField(
            model_name='clientreproductivehealthdata',
            name='reason_not_using_fp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.ReasonNotUsingFamilyPlanning', verbose_name='Why are you not using any family planning method?'),
        ),
        migrations.AlterField(
            model_name='clientreproductivehealthdata',
            name='reason_not_using_fp_other',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Reason not using modern family planning method(Other)'),
        ),
    ]
