# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-27 10:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DreamsApp', '0011_auto_20161027_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdrugusedata',
            name='drug_used_last_12months',
            field=models.ManyToManyField(blank=True, to='DreamsApp.Drug'),
        ),
        migrations.AlterField(
            model_name='clientdrugusedata',
            name='frequency_of_alcohol_last_12months',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DreamsApp.FrequencyResponse'),
        ),
        migrations.AlterField(
            model_name='clienteducationandemploymentdata',
            name='banking_place_other',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Other place for savings'),
        ),
        migrations.AlterField(
            model_name='clienteducationandemploymentdata',
            name='current_income_source_other',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Source of income(other)'),
        ),
        migrations.AlterField(
            model_name='clienteducationandemploymentdata',
            name='dropout_class',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Drop out Class'),
        ),
        migrations.AlterField(
            model_name='clienteducationandemploymentdata',
            name='dropout_school_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.SchoolLevel'),
        ),
        migrations.AlterField(
            model_name='clienteducationandemploymentdata',
            name='life_wish',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.LifeWish', verbose_name='Wish in Life'),
        ),
        migrations.AlterField(
            model_name='clienteducationandemploymentdata',
            name='reason_not_in_school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.ReasonNotInSchool', verbose_name='Reason for not going to School'),
        ),
        migrations.AlterField(
            model_name='clienteducationandemploymentdata',
            name='reason_not_in_school_other',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Reason for not going to school(other)'),
        ),
        migrations.AlterField(
            model_name='clientgenderbasedviolencedata',
            name='economic_threat_ever',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.CategoricalResponse'),
        ),
        migrations.AlterField(
            model_name='clientgenderbasedviolencedata',
            name='gbv_help_provider_other',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Other source of GBV help'),
        ),
        migrations.AlterField(
            model_name='clientgenderbasedviolencedata',
            name='humiliated_ever',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.CategoricalResponse'),
        ),
        migrations.AlterField(
            model_name='clientgenderbasedviolencedata',
            name='insulted_ever',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.CategoricalResponse'),
        ),
        migrations.AlterField(
            model_name='clientgenderbasedviolencedata',
            name='physical_violence_ever',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.CategoricalResponse'),
        ),
        migrations.AlterField(
            model_name='clientgenderbasedviolencedata',
            name='physically_forced_other_sex_acts_ever',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.CategoricalResponse'),
        ),
        migrations.AlterField(
            model_name='clientgenderbasedviolencedata',
            name='physically_forced_sex_ever',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.CategoricalResponse'),
        ),
        migrations.AlterField(
            model_name='clientgenderbasedviolencedata',
            name='threatened_for_sexual_acts_ever',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.CategoricalResponse'),
        ),
        migrations.AlterField(
            model_name='clientgenderbasedviolencedata',
            name='threats_to_hurt_ever',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.CategoricalResponse'),
        ),
        migrations.AlterField(
            model_name='clientindividualandhouseholddata',
            name='currently_in_ct_program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.CategoricalResponse', verbose_name='Currently enrolled in Cash Transfer?'),
        ),
        migrations.AlterField(
            model_name='clientsexualactivitydata',
            name='age_at_first_sexual_encounter',
            field=models.IntegerField(blank=True, null=True, verbose_name='Age at first sexual encounter'),
        ),
        migrations.AlterField(
            model_name='clientsexualactivitydata',
            name='sex_partners_in_last_12months',
            field=models.IntegerField(blank=True, null=True, verbose_name='Sexual partners in the last 12 months'),
        ),
    ]
