# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-28 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DreamsApp', '0011_auto_20160428_0607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maritalstatus',
            name='code',
            field=models.CharField(max_length=10, verbose_name='Marital Status Code'),
        ),
    ]
