# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-27 12:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DreamsApp', '0012_auto_20161027_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienthivtestingdata',
            name='last_test_result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.HivTestResultResponse', verbose_name='Last Test Result'),
        ),
        migrations.AlterField(
            model_name='clienthivtestingdata',
            name='period_last_tested',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.PeriodResponse', verbose_name='Period last Tested'),
        ),
        migrations.AlterField(
            model_name='clientsexualactivitydata',
            name='has_sexual_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.CategoricalResponse'),
        ),
    ]
