# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-10 10:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('DreamsApp', '0012_auto_20160428_1001'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(verbose_name='Verification Document Code')),
                ('name', models.CharField(max_length=150, verbose_name='Verification Document Name')),
            ],
            options={
                'verbose_name': 'Verification Document',
                'verbose_name_plural': 'Verification Documents',
            },
        ),
        migrations.AddField(
            model_name='client',
            name='verification_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='DreamsApp.VerificationDocument'),
        ),
    ]
