# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-10 10:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DreamsApp', '0013_auto_20160510_1026'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImplementingPartner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(verbose_name='Implementing Partner Code')),
                ('name', models.CharField(max_length=150, verbose_name='Implementing Partner Name')),
            ],
            options={
                'verbose_name': 'Implementing Partner',
                'verbose_name_plural': 'Implementing Partners',
            },
        ),
        migrations.AddField(
            model_name='client',
            name='implementing_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DreamsApp.ImplementingPartner'),
        ),
    ]
