# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-10 11:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DreamsApp', '0014_auto_20160510_1035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ward',
            old_name='county',
            new_name='sub_county',
        ),
    ]
