# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-13 05:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DreamsApp', '0015_auto_20160510_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcounty',
            name='code',
            field=models.CharField(default='', max_length=100, verbose_name='Sub County Code'),
        ),
        migrations.AlterField(
            model_name='ward',
            name='code',
            field=models.CharField(default='', max_length=100, verbose_name='Ward Code'),
        ),
    ]
