# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-04 05:50
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DreamsApp', '0016_auto_20161102_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='county_of_residence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DreamsApp.County', verbose_name='County of Residence'),
        ),
        migrations.AlterField(
            model_name='client',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='client',
            name='date_of_enrollment',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Date of Enrollment'),
        ),
        migrations.AlterField(
            model_name='client',
            name='dreams_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='DREAMS ID'),
        ),
        migrations.AlterField(
            model_name='client',
            name='enrolled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='client',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='client',
            name='implementing_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DreamsApp.ImplementingPartner', verbose_name='Implementing Partner'),
        ),
        migrations.AlterField(
            model_name='client',
            name='marital_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DreamsApp.MaritalStatus', verbose_name='Marital Status'),
        ),
        migrations.AlterField(
            model_name='client',
            name='sub_county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DreamsApp.SubCounty', verbose_name='Sub County'),
        ),
        migrations.AlterField(
            model_name='client',
            name='verification_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DreamsApp.VerificationDocument', verbose_name='Verification Document'),
        ),
        migrations.AlterField(
            model_name='client',
            name='village',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Village'),
        ),
        migrations.AlterField(
            model_name='client',
            name='ward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DreamsApp.Ward', verbose_name='Ward'),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='date_voided',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
