# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-26 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DreamsApp', '0016_auto_20160513_0557'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('user_id', models.IntegerField()),
                ('table', models.CharField(default='', max_length=200)),
                ('row_id', models.IntegerField(blank=True, null=True)),
                ('action', models.CharField(max_length=100)),
                ('search_text', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'verbose_name': 'Audit',
                'verbose_name_plural': 'Audit log',
            },
        ),
    ]
