# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-07 01:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DreamsApp', '0018_implementingpartneruser'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervention',
            name='implementing_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='implementing_partner', to='DreamsApp.ImplementingPartner'),
        ),
    ]
