# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-14 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DreamsApp', '0020_auto_20161114_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='voided',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='clientdrugusedata',
            name='voided',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='clienteducationandemploymentdata',
            name='voided',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='clientgenderbasedviolencedata',
            name='voided',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='clienthivtestingdata',
            name='voided',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='clientindividualandhouseholddata',
            name='voided',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='clientparticipationindreams',
            name='voided',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='clientreproductivehealthdata',
            name='voided',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='clientsexualactivitydata',
            name='voided',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='voided',
            field=models.NullBooleanField(default=False),
        ),
    ]
