# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-25 09:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DreamsApp', '0021_auto_20161114_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienteducationandemploymentdata',
            name='current_income_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.SourceOfIncome', verbose_name='Current source of Income'),
        ),
        migrations.AlterField(
            model_name='clienteducationandemploymentdata',
            name='has_savings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.CategoricalResponse', verbose_name='Do you have savings?'),
        ),
        migrations.AlterField(
            model_name='clienteducationandemploymentdata',
            name='last_time_in_school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.PeriodResponse', verbose_name='Last time in School'),
        ),
        migrations.AlterField(
            model_name='clienteducationandemploymentdata',
            name='life_wish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.LifeWish', verbose_name='Wish in Life'),
        ),
        migrations.AlterField(
            model_name='clienthivtestingdata',
            name='knowledge_of_hiv_test_centres',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.CategoricalResponse', verbose_name='Know places where people get tested for HIV?'),
        ),
        migrations.AlterField(
            model_name='clientreproductivehealthdata',
            name='currently_pregnant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.CategoricalResponse', verbose_name='Are you currently pregnant?'),
        ),
        migrations.AlterField(
            model_name='clientreproductivehealthdata',
            name='has_biological_children',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.CategoricalResponse', verbose_name='Do you have biological children?'),
        ),
    ]
