# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-13 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DreamsApp', '0021_auto_20160707_0125'),
    ]

    operations = [
        migrations.CreateModel(
            name='InitApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('inited', models.BooleanField(default=False)),
            ],
        ),
    ]
