# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-10 08:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DreamsApp', '0022_initapp'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeOfSexualPartner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Age Category')),
                ('code', models.IntegerField(verbose_name='Code')),
            ],
            options={
                'verbose_name_plural': 'Age of Sexual Partner ',
            },
        ),
        migrations.CreateModel(
            name='BankingPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Banking Place')),
                ('code', models.IntegerField(verbose_name='Code')),
            ],
            options={
                'verbose_name': 'Banking Place',
                'verbose_name_plural': 'Banking Places',
            },
        ),
        migrations.CreateModel(
            name='CategoricalResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Response Name')),
                ('code', models.IntegerField(verbose_name='Response Code')),
            ],
            options={
                'verbose_name': 'Yes|No Response',
                'verbose_name_plural': 'Yes|No Responses',
            },
        ),
        migrations.CreateModel(
            name='ClientDrugUseData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_abuse_last_12months_other', models.CharField(blank=True, max_length=50, null=True)),
                ('drug_used_last_12months_other', models.CharField(blank=True, max_length=50, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DreamsApp.Client')),
                ('drug_abuse_last_12months', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.CategoricalResponse')),
            ],
        ),
        migrations.CreateModel(
            name='ClientEducationAndEmploymentData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_school_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Name of school')),
                ('current_class', models.CharField(blank=True, max_length=10, null=True, verbose_name='Class')),
                ('current_school_level_other', models.CharField(blank=True, max_length=20, null=True, verbose_name='Other Education Level')),
                ('current_education_supporter_other', models.CharField(blank=True, max_length=25, null=True, verbose_name='Support towards current education: other')),
                ('reason_not_in_school_other', models.CharField(max_length=50, verbose_name='Reason for not going to school: other')),
                ('dropout_class', models.CharField(max_length=15, verbose_name='Drop out class')),
                ('life_wish_other', models.CharField(blank=True, max_length=50, null=True, verbose_name='Wish in life: other')),
                ('current_income_source_other', models.CharField(max_length=30, verbose_name='Source of income: other')),
                ('banking_place_other', models.CharField(max_length=20, verbose_name='Other place for savings')),
                ('banking_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.BankingPlace', verbose_name='Where do you keep your savings?')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DreamsApp.Client')),
            ],
        ),
        migrations.CreateModel(
            name='ClientGenderBasedViolenceData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gbv_help_provider_other', models.CharField(max_length=50, verbose_name='Other source of GBV help')),
                ('preferred_gbv_help_provider_other', models.CharField(blank=True, max_length=50, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DreamsApp.Client')),
                ('economic_threat_ever', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.CategoricalResponse')),
            ],
        ),
        migrations.CreateModel(
            name='ClientHIVTestingData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('care_facility_enrolled', models.CharField(blank=True, max_length=50)),
                ('reason_not_in_hiv_care_other', models.CharField(blank=True, max_length=50, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DreamsApp.Client')),
                ('enrolled_in_hiv_care', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.CategoricalResponse')),
                ('ever_tested_for_hiv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.CategoricalResponse')),
                ('knowledge_of_hiv_test_centres', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.CategoricalResponse')),
            ],
        ),
        migrations.CreateModel(
            name='ClientIndividualAndHouseholdData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_of_household_other', models.CharField(blank=True, max_length=50, null=True)),
                ('age_of_household_head', models.IntegerField(blank=True, default=0)),
                ('is_father_alive', models.IntegerField(verbose_name='Father alive?')),
                ('is_mother_alive', models.IntegerField(verbose_name='Mother alive?')),
                ('is_parent_chronically_ill', models.IntegerField(verbose_name='Is any of your parent/guardian chronically ill?')),
                ('main_floor_material_other', models.CharField(blank=True, max_length=50, null=True, verbose_name='Main floor material: other')),
                ('main_roof_material_other', models.CharField(blank=True, max_length=50, null=True, verbose_name='Main roof material: other')),
                ('main_wall_material_other', models.CharField(blank=True, max_length=50, null=True, verbose_name='Main wall material: other')),
                ('source_of_drinking_water_other', models.CharField(blank=True, max_length=50, null=True, verbose_name='Main source of drinking water: other')),
                ('disability_type_other', models.CharField(blank=True, max_length=50, null=True, verbose_name='Other disability type')),
                ('no_of_people_in_household', models.IntegerField(verbose_name='No of people living in your house')),
                ('no_of_females', models.IntegerField(verbose_name='No of females')),
                ('no_of_males', models.IntegerField(verbose_name='No of Males')),
                ('no_adults', models.IntegerField(verbose_name='No of adults')),
                ('no_children', models.IntegerField(verbose_name='No of children')),
                ('current_ct_program', models.CharField(max_length=50, verbose_name='Cash Transfer Programme currently enrolled in')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DreamsApp.Client')),
                ('currently_in_ct_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.CategoricalResponse', verbose_name='Currently enrolled in Cash Transfer?')),
            ],
        ),
        migrations.CreateModel(
            name='ClientParticipationInDreams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dreams_program_other', models.CharField(blank=True, max_length=50, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DreamsApp.Client')),
            ],
        ),
        migrations.CreateModel(
            name='ClientReproductiveHealthData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_biological_children', models.IntegerField(blank=True, null=True)),
                ('anc_facility_name', models.CharField(blank=True, max_length=50, null=True)),
                ('known_fp_method_other', models.CharField(blank=True, max_length=50, null=True)),
                ('current_fp_method_other', models.CharField(blank=True, max_length=50, null=True, verbose_name='Other Modern FP method used')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DreamsApp.Client')),
                ('current_anc_enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.CategoricalResponse')),
            ],
        ),
        migrations.CreateModel(
            name='ClientSexualActivityData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_at_first_sexual_encounter', models.IntegerField(verbose_name='Age at first sexual encounter')),
                ('sex_partners_in_last_12months', models.IntegerField(verbose_name='Sexual partners in the last 12 months')),
                ('age_of_last_partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.AgeOfSexualPartner')),
                ('age_of_second_last_partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.AgeOfSexualPartner')),
                ('age_of_third_last_partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.AgeOfSexualPartner')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DreamsApp.Client')),
                ('ever_had_sex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.CategoricalResponse')),
                ('has_sexual_partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.CategoricalResponse')),
                ('know_last_partner_hiv_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.CategoricalResponse')),
                ('know_second_last_partner_hiv_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.CategoricalResponse')),
                ('know_third_last_partner_hiv_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.CategoricalResponse')),
                ('last_partner_circumcised', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.CategoricalResponse')),
                ('received_money_gift_for_sex', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.CategoricalResponse')),
                ('second_last_partner_circumcised', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.CategoricalResponse')),
                ('third_last_partner_circumcised', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.CategoricalResponse')),
            ],
        ),
        migrations.CreateModel(
            name='DisabilityType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name of Disability')),
                ('code', models.IntegerField(verbose_name='Disability Code')),
            ],
            options={
                'verbose_name': 'Disability Type',
                'verbose_name_plural': 'Disability Types',
            },
        ),
        migrations.CreateModel(
            name='DreamsProgramme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name of Programme')),
                ('code', models.IntegerField(verbose_name='Code')),
            ],
            options={
                'verbose_name': 'Dreams Programme',
                'verbose_name_plural': 'Dreams Programmes',
            },
        ),
        migrations.CreateModel(
            name='DrinkingWater',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Water Source')),
                ('code', models.IntegerField(verbose_name='Source Code')),
            ],
            options={
                'verbose_name': 'Drinking Water Source',
                'verbose_name_plural': 'Drinking water Sources',
            },
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Drug Abuse/Addiction')),
                ('code', models.IntegerField(verbose_name='Code')),
            ],
            options={
                'verbose_name_plural': 'Drug Abuse',
            },
        ),
        migrations.CreateModel(
            name='EducationSupporter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('code', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Source of Education Support',
                'verbose_name_plural': 'Sources of Education Support',
            },
        ),
        migrations.CreateModel(
            name='FamilyPlanningMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Method')),
                ('code', models.IntegerField(verbose_name='Code')),
            ],
            options={
                'verbose_name': 'Family Planning method',
                'verbose_name_plural': 'Family Planning methods',
            },
        ),
        migrations.CreateModel(
            name='FloorMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Material Name')),
                ('code', models.IntegerField(verbose_name='Material Code')),
            ],
            options={
                'verbose_name': 'Main Floor Material',
                'verbose_name_plural': 'Main Floor Materials',
            },
        ),
        migrations.CreateModel(
            name='FrequencyResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Frequency')),
                ('code', models.IntegerField(verbose_name='Code')),
            ],
            options={
                'verbose_name': 'Frequency Response',
                'verbose_name_plural': 'Frequency Responses',
            },
        ),
        migrations.CreateModel(
            name='GBVHelpProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Source of Support')),
                ('code', models.IntegerField(verbose_name='Code')),
            ],
            options={
                'verbose_name': 'Source of GBV Support',
                'verbose_name_plural': 'Sources of GBV Support',
            },
        ),
        migrations.CreateModel(
            name='HivTestResultResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Response')),
                ('code', models.IntegerField(verbose_name='Code')),
            ],
            options={
                'verbose_name': 'HIV Test Response',
                'verbose_name_plural': 'HIV Test Responses',
            },
        ),
        migrations.CreateModel(
            name='HouseholdHead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.IntegerField(verbose_name='Household Head Code')),
            ],
            options={
                'verbose_name': 'Head of Household Category',
                'verbose_name_plural': 'Head of Household Categories',
            },
        ),
        migrations.CreateModel(
            name='LifeWish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Wish')),
                ('code', models.IntegerField(verbose_name='Wish Code')),
            ],
            options={
                'verbose_name': 'Life Wish',
                'verbose_name_plural': 'Life Wishes',
            },
        ),
        migrations.CreateModel(
            name='PeriodResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Response Name')),
                ('code', models.IntegerField(verbose_name='Response Code')),
            ],
            options={
                'verbose_name': 'Duration Response',
                'verbose_name_plural': 'Duration Responses',
            },
        ),
        migrations.CreateModel(
            name='ReasonNotInHIVCare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Response')),
                ('code', models.IntegerField(verbose_name='Code')),
            ],
            options={
                'verbose_name': 'Reason not in HIV Care',
                'verbose_name_plural': 'Reasons not in HIV Care',
            },
        ),
        migrations.CreateModel(
            name='ReasonNotInSchool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Reason')),
                ('code', models.IntegerField(verbose_name='Reason Code')),
            ],
            options={
                'verbose_name': 'Reason not in School',
                'verbose_name_plural': 'Reasons not in School',
            },
        ),
        migrations.CreateModel(
            name='ReasonNotTestedForHIV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Response')),
                ('code', models.IntegerField(verbose_name='Code')),
            ],
            options={
                'verbose_name': 'Reason not tested for HIV',
                'verbose_name_plural': 'Reasons not tested for HIV ',
            },
        ),
        migrations.CreateModel(
            name='ReasonNotUsingFamilyPlanning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Reason')),
                ('code', models.IntegerField(verbose_name='Code')),
            ],
            options={
                'verbose_name': 'Reason not using Family Planning',
                'verbose_name_plural': 'Reasons not using Family Planning',
            },
        ),
        migrations.CreateModel(
            name='RoofingMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Material Name')),
                ('code', models.IntegerField(verbose_name='Material Code')),
            ],
            options={
                'verbose_name': 'Main Roofing Material',
                'verbose_name_plural': 'Main Roofing Materials',
            },
        ),
        migrations.CreateModel(
            name='SchoolLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Education Level Name')),
                ('code', models.IntegerField(verbose_name='Education Level Code')),
            ],
            options={
                'verbose_name': 'Level of Education',
                'verbose_name_plural': 'Levels of Education',
            },
        ),
        migrations.CreateModel(
            name='SchoolType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.IntegerField(verbose_name='Type Code')),
            ],
            options={
                'verbose_name': 'School Type',
                'verbose_name_plural': 'School Types',
            },
        ),
        migrations.CreateModel(
            name='SourceOfIncome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Source')),
                ('code', models.IntegerField(verbose_name='Code')),
            ],
            options={
                'verbose_name': 'Source of Income',
                'verbose_name_plural': 'Sources of Income',
            },
        ),
        migrations.CreateModel(
            name='WallMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Material Name')),
                ('code', models.IntegerField(verbose_name='Material Code')),
            ],
            options={
                'verbose_name': 'Main Wall Material',
                'verbose_name_plural': 'Main Wall Materials',
            },
        ),
        migrations.AddField(
            model_name='intervention',
            name='name_specified',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='interventiontype',
            name='is_age_restricted',
            field=models.BooleanField(default=False, verbose_name='Intervention is Age Restricted'),
        ),
        migrations.AddField(
            model_name='interventiontype',
            name='is_given_once',
            field=models.BooleanField(default=False, verbose_name='Intervention is given Once'),
        ),
        migrations.AddField(
            model_name='interventiontype',
            name='is_specified',
            field=models.BooleanField(default=False, verbose_name='Intervention is specified'),
        ),
        migrations.AddField(
            model_name='interventiontype',
            name='max_age',
            field=models.IntegerField(default=0, verbose_name='Maximum AGYW Age'),
        ),
        migrations.AddField(
            model_name='interventiontype',
            name='min_age',
            field=models.IntegerField(default=0, verbose_name='Minimum AGYW Age'),
        ),
        migrations.AddField(
            model_name='clientsexualactivitydata',
            name='used_condom_with_last_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.FrequencyResponse'),
        ),
        migrations.AddField(
            model_name='clientsexualactivitydata',
            name='used_condom_with_second_last_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.FrequencyResponse'),
        ),
        migrations.AddField(
            model_name='clientsexualactivitydata',
            name='used_condom_with_third_last_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.FrequencyResponse'),
        ),
        migrations.AddField(
            model_name='clientreproductivehealthdata',
            name='current_fp_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.FamilyPlanningMethod'),
        ),
        migrations.AddField(
            model_name='clientreproductivehealthdata',
            name='currently_pregnant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.CategoricalResponse'),
        ),
        migrations.AddField(
            model_name='clientreproductivehealthdata',
            name='currently_use_modern_fp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.CategoricalResponse'),
        ),
        migrations.AddField(
            model_name='clientreproductivehealthdata',
            name='fp_methods_awareness',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.CategoricalResponse'),
        ),
        migrations.AddField(
            model_name='clientreproductivehealthdata',
            name='has_biological_children',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.CategoricalResponse'),
        ),
        migrations.AddField(
            model_name='clientreproductivehealthdata',
            name='known_fp_method',
            field=models.ManyToManyField(blank=True, related_name='_clientreproductivehealthdata_known_fp_method_+', to='DreamsApp.FamilyPlanningMethod'),
        ),
        migrations.AddField(
            model_name='clientparticipationindreams',
            name='dreams_program',
            field=models.ManyToManyField(blank=True, to='DreamsApp.DreamsProgramme'),
        ),
        migrations.AddField(
            model_name='clientindividualandhouseholddata',
            name='disability_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.DisabilityType', verbose_name='Disability Type'),
        ),
        migrations.AddField(
            model_name='clientindividualandhouseholddata',
            name='ever_enrolled_in_ct_program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.CategoricalResponse', verbose_name='Ever enrolled in Cash Transfer?'),
        ),
        migrations.AddField(
            model_name='clientindividualandhouseholddata',
            name='ever_missed_full_day_food_in_4wks',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.CategoricalResponse'),
        ),
        migrations.AddField(
            model_name='clientindividualandhouseholddata',
            name='has_disability',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.CategoricalResponse', verbose_name='Disabled?'),
        ),
        migrations.AddField(
            model_name='clientindividualandhouseholddata',
            name='head_of_household',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.HouseholdHead'),
        ),
        migrations.AddField(
            model_name='clientindividualandhouseholddata',
            name='main_floor_material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.FloorMaterial', verbose_name='Main floor material'),
        ),
        migrations.AddField(
            model_name='clientindividualandhouseholddata',
            name='main_roof_material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.RoofingMaterial', verbose_name='Main roof material'),
        ),
        migrations.AddField(
            model_name='clientindividualandhouseholddata',
            name='main_wall_material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.RoofingMaterial', verbose_name='Main wall material'),
        ),
        migrations.AddField(
            model_name='clientindividualandhouseholddata',
            name='no_of_days_missed_food_in_4wks',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.FrequencyResponse'),
        ),
        migrations.AddField(
            model_name='clientindividualandhouseholddata',
            name='source_of_drinking_water',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.DrinkingWater', verbose_name='Main source of drinking water'),
        ),
        migrations.AddField(
            model_name='clienthivtestingdata',
            name='last_test_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.HivTestResultResponse'),
        ),
        migrations.AddField(
            model_name='clienthivtestingdata',
            name='period_last_tested',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.PeriodResponse'),
        ),
        migrations.AddField(
            model_name='clienthivtestingdata',
            name='reason_never_tested_for_hiv',
            field=models.ManyToManyField(blank=True, to='DreamsApp.ReasonNotTestedForHIV'),
        ),
        migrations.AddField(
            model_name='clienthivtestingdata',
            name='reason_not_in_hiv_care',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.ReasonNotInHIVCare'),
        ),
        migrations.AddField(
            model_name='clientgenderbasedviolencedata',
            name='economic_threat_last_3months',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.FrequencyResponse'),
        ),
        migrations.AddField(
            model_name='clientgenderbasedviolencedata',
            name='gbv_help_provider',
            field=models.ManyToManyField(blank=True, related_name='_clientgenderbasedviolencedata_gbv_help_provider_+', to='DreamsApp.GBVHelpProvider'),
        ),
        migrations.AddField(
            model_name='clientgenderbasedviolencedata',
            name='humiliated_ever',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.CategoricalResponse'),
        ),
        migrations.AddField(
            model_name='clientgenderbasedviolencedata',
            name='humiliated_last_3months',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.FrequencyResponse'),
        ),
        migrations.AddField(
            model_name='clientgenderbasedviolencedata',
            name='insulted_ever',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.CategoricalResponse'),
        ),
        migrations.AddField(
            model_name='clientgenderbasedviolencedata',
            name='insulted_last_3months',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.FrequencyResponse'),
        ),
        migrations.AddField(
            model_name='clientgenderbasedviolencedata',
            name='knowledge_of_gbv_help_centres',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.CategoricalResponse'),
        ),
        migrations.AddField(
            model_name='clientgenderbasedviolencedata',
            name='physical_violence_ever',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.CategoricalResponse'),
        ),
        migrations.AddField(
            model_name='clientgenderbasedviolencedata',
            name='physical_violence_last_3months',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.FrequencyResponse'),
        ),
        migrations.AddField(
            model_name='clientgenderbasedviolencedata',
            name='physically_forced_other_sex_acts_ever',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.CategoricalResponse'),
        ),
        migrations.AddField(
            model_name='clientgenderbasedviolencedata',
            name='physically_forced_other_sex_acts_last_3months',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.FrequencyResponse'),
        ),
        migrations.AddField(
            model_name='clientgenderbasedviolencedata',
            name='physically_forced_sex_ever',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.CategoricalResponse'),
        ),
        migrations.AddField(
            model_name='clientgenderbasedviolencedata',
            name='physically_forced_sex_last_3months',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.FrequencyResponse'),
        ),
        migrations.AddField(
            model_name='clientgenderbasedviolencedata',
            name='preferred_gbv_help_provider',
            field=models.ManyToManyField(blank=True, related_name='_clientgenderbasedviolencedata_preferred_gbv_help_provider_+', to='DreamsApp.GBVHelpProvider'),
        ),
        migrations.AddField(
            model_name='clientgenderbasedviolencedata',
            name='seek_help_after_gbv',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.CategoricalResponse'),
        ),
        migrations.AddField(
            model_name='clientgenderbasedviolencedata',
            name='threatened_for_sexual_acts_ever',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.CategoricalResponse'),
        ),
        migrations.AddField(
            model_name='clientgenderbasedviolencedata',
            name='threatened_for_sexual_acts_last_3months',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.FrequencyResponse'),
        ),
        migrations.AddField(
            model_name='clientgenderbasedviolencedata',
            name='threats_to_hurt_ever',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.CategoricalResponse'),
        ),
        migrations.AddField(
            model_name='clientgenderbasedviolencedata',
            name='threats_to_hurt_last_3months',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.FrequencyResponse'),
        ),
        migrations.AddField(
            model_name='clienteducationandemploymentdata',
            name='current_education_supporter',
            field=models.ManyToManyField(blank=True, to='DreamsApp.EducationSupporter'),
        ),
        migrations.AddField(
            model_name='clienteducationandemploymentdata',
            name='current_income_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.SourceOfIncome', verbose_name='Current source of income'),
        ),
        migrations.AddField(
            model_name='clienteducationandemploymentdata',
            name='current_school_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.SchoolLevel', verbose_name='Current school level'),
        ),
        migrations.AddField(
            model_name='clienteducationandemploymentdata',
            name='current_school_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.SchoolType', verbose_name='Type of school'),
        ),
        migrations.AddField(
            model_name='clienteducationandemploymentdata',
            name='currently_in_school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.CategoricalResponse', verbose_name='Currently schooling'),
        ),
        migrations.AddField(
            model_name='clienteducationandemploymentdata',
            name='dropout_school_level',
            field=models.ForeignKey(on_delete='id', related_name='+', to='DreamsApp.SchoolLevel', to_field='In which class/form did you stop schooling?'),
        ),
        migrations.AddField(
            model_name='clienteducationandemploymentdata',
            name='has_savings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.CategoricalResponse', verbose_name='Do you have savings?'),
        ),
        migrations.AddField(
            model_name='clienteducationandemploymentdata',
            name='last_time_in_school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.PeriodResponse', verbose_name='Last time in school'),
        ),
        migrations.AddField(
            model_name='clienteducationandemploymentdata',
            name='life_wish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.LifeWish', verbose_name='Wish in life'),
        ),
        migrations.AddField(
            model_name='clienteducationandemploymentdata',
            name='reason_not_in_school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.ReasonNotInSchool', verbose_name='Reason for not going to school'),
        ),
        migrations.AddField(
            model_name='clientdrugusedata',
            name='drug_used_last_12months',
            field=models.ManyToManyField(to='DreamsApp.Drug'),
        ),
        migrations.AddField(
            model_name='clientdrugusedata',
            name='frequency_of_alcohol_last_12months',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DreamsApp.FrequencyResponse'),
        ),
        migrations.AddField(
            model_name='clientdrugusedata',
            name='produced_alcohol_last_12months',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.CategoricalResponse'),
        ),
        migrations.AddField(
            model_name='clientdrugusedata',
            name='used_alcohol_last_12months',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.CategoricalResponse'),
        ),
    ]
