# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-25 09:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DreamsApp', '0022_auto_20161125_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienthivtestingdata',
            name='ever_tested_for_hiv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.CategoricalResponse', verbose_name='Ever Tested for HIV'),
        ),
        migrations.AlterField(
            model_name='clientreproductivehealthdata',
            name='currently_use_modern_fp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.CategoricalResponse', verbose_name='Are you currently using any modern family planning method?'),
        ),
        migrations.AlterField(
            model_name='clientreproductivehealthdata',
            name='fp_methods_awareness',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.CategoricalResponse', verbose_name='Are you aware of any family planning methods?'),
        ),
        migrations.AlterField(
            model_name='clientsexualactivitydata',
            name='ever_had_sex',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DreamsApp.CategoricalResponse'),
        ),
    ]
