# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-21 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DreamsApp', '0022_initapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='interventiontype',
            name='is_given_once',
            field=models.BooleanField(default=False, verbose_name='Intervention is given Once'),
        ),
        migrations.AddField(
            model_name='interventiontype',
            name='max_age',
            field=models.IntegerField(default=0, verbose_name='Maximum AGYW Age'),
        ),
        migrations.AddField(
            model_name='interventiontype',
            name='min_age',
            field=models.IntegerField(default=0, verbose_name='Minimum AGYW Age'),
        ),
    ]
