# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-04 05:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('DreamsApp', '0023_auto_20161125_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='date_exited',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='exited',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='exited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='client',
            name='reason_exited',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
