# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-21 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DreamsApp', '0023_auto_20160721_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='interventiontype',
            name='is_age_restricted',
            field=models.BooleanField(default=False, verbose_name='Intervention is Age Restricted'),
        ),
    ]
