# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-03 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DreamsApp', '0024_interventiontype_is_age_restricted'),
    ]

    operations = [
        migrations.AddField(
            model_name='interventiontype',
            name='is_specified',
            field=models.BooleanField(default=False, verbose_name='Intervention is specified'),
        ),
    ]
