# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-02-06 17:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('DreamsApp', '0025_auto_20170720_0810'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditTrail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column', models.CharField(max_length=50)),
                ('old_value', models.CharField(blank=True, max_length=250, null=True)),
                ('new_value', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'verbose_name': 'Audit Trail',
                'verbose_name_plural': 'Audit Trails',
            },
        ),
        migrations.RemoveField(
            model_name='audit',
            name='user_id',
        ),
        migrations.AddField(
            model_name='audit',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='audittrail',
            name='audit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DreamsApp.Audit'),
        ),
    ]
