# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-04-05 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DreamsApp', '0026_auto_20180206_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='exited',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='client',
            name='voided',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='clientdrugusedata',
            name='voided',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='clienteducationandemploymentdata',
            name='voided',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='clientgenderbasedviolencedata',
            name='voided',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='clienthivtestingdata',
            name='voided',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='clientindividualandhouseholddata',
            name='voided',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='clientparticipationindreams',
            name='voided',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='clientreproductivehealthdata',
            name='voided',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='clientsexualactivitydata',
            name='voided',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='voided',
            field=models.BooleanField(default=False),
        ),
    ]
