# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-03 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DreamsApp', '0026_interventiontype_name_specified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interventiontype',
            name='name_specified',
        ),
        migrations.AddField(
            model_name='intervention',
            name='name_specified',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
