# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-12 06:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DreamsApp', '0027_auto_20160803_0915'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InitApp',
        ),
    ]
