# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-04-23 09:35
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DreamsApp', '0027_auto_20180405_1809'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterventionPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Code')),
                ('name', models.CharField(max_length=50, verbose_name='Package Name')),
            ],
            options={
                'verbose_name': 'Intervention Package',
                'verbose_name_plural': 'Intervention Packages',
            },
        ),
        migrations.CreateModel(
            name='InterventionTypePackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lower_age_limit', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(24)], verbose_name='Lower age limit')),
                ('upper_age_limit', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(24)], verbose_name='Upper age limit')),
                ('intervention_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DreamsApp.InterventionPackage')),
                ('intervention_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DreamsApp.InterventionType')),
            ],
            options={
                'verbose_name': 'InterventionType Package',
                'verbose_name_plural': 'InterventionType Packages',
            },
        ),
        migrations.AddField(
            model_name='interventionpackage',
            name='intervention_types',
            field=models.ManyToManyField(through='DreamsApp.InterventionTypePackage', to='DreamsApp.InterventionType'),
        ),
    ]
