# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-12 07:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('DreamsApp', '0028_delete_initapp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grievance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date Reported')),
                ('reporter_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Reporter Name')),
                ('dreams_id', models.CharField(blank=True, max_length=150, null=True, verbose_name='DREAMS ID')),
                ('relationship', models.CharField(blank=True, max_length=50, null=True, verbose_name='Relationship')),
                ('other_specify', models.CharField(blank=True, max_length=150, null=True, verbose_name='Specify')),
                ('reporter_phone', models.CharField(max_length=13, null=True, verbose_name='Complainant\u2019s Telephone No:')),
                ('received_by', models.CharField(blank=True, max_length=250, null=True, verbose_name='Name of DREAMS staff receiving the grievance')),
                ('receiver_designation', models.CharField(blank=True, max_length=50, null=True, verbose_name='Designation')),
                ('is_first_time_complaint', models.BooleanField(default=False, verbose_name='Is a 1st Time Complaint')),
                ('person_responsible', models.CharField(blank=True, max_length=250, null=True, verbose_name='Person Responsible')),
                ('resolution', models.TextField(blank=True, null=True, verbose_name='Resolution')),
                ('resolution_date', models.DateField(verbose_name='Date of resolution')),
                ('complainant_feedback_date', models.DateField(verbose_name='Date Feedback to complainant')),
                ('is_open', models.BooleanField(default=True, verbose_name='Status')),
                ('closed_by', models.CharField(blank=True, max_length=250, null=True, verbose_name='Closed by')),
                ('closure_date', models.DateField(verbose_name='Date Closed')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('county', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='county', to='DreamsApp.County', verbose_name='County')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Grievance',
                'verbose_name_plural': 'Grievances',
            },
        ),
        migrations.CreateModel(
            name='GrievanceNature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(verbose_name='Code')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Nature of Grievance',
                'verbose_name_plural': 'Nature of Grievance List',
            },
        ),
        migrations.CreateModel(
            name='GrievanceReporterCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(verbose_name='Code')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('requires_dreams_id', models.BooleanField(default=False, verbose_name='Requires DREAMS ID')),
                ('requires_relationship', models.BooleanField(default=False, verbose_name='Requires Relationship Specification')),
                ('is_other_specified', models.BooleanField(default=False, verbose_name='Other Specify')),
            ],
            options={
                'verbose_name': 'Grievance Reporter Category',
                'verbose_name_plural': 'Grievance Reporter Categories',
            },
        ),
        migrations.AddField(
            model_name='grievance',
            name='grievance_nature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grievance_nature', to='DreamsApp.GrievanceNature', verbose_name='Nature of Grievance'),
        ),
        migrations.AddField(
            model_name='grievance',
            name='implementing_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DreamsApp.ImplementingPartner', verbose_name='Implementing Partner'),
        ),
        migrations.AddField(
            model_name='grievance',
            name='modified_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By'),
        ),
        migrations.AddField(
            model_name='grievance',
            name='reporter_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reporter_category', to='DreamsApp.GrievanceReporterCategory', verbose_name='Reporter Category'),
        ),
        migrations.AddField(
            model_name='grievance',
            name='ward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ward', to='DreamsApp.Ward', verbose_name='Ward'),
        ),
    ]
