# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-13 01:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DreamsApp', '0029_auto_20160812_0753'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grievance',
            options={'ordering': ['-date'], 'verbose_name': 'Grievance', 'verbose_name_plural': 'Grievances'},
        ),
        migrations.AlterModelOptions(
            name='grievancenature',
            options={'verbose_name': 'Nature of Grievance', 'verbose_name_plural': 'Grievance Nature List'},
        ),
        migrations.AddField(
            model_name='grievancenature',
            name='is_other_specify',
            field=models.BooleanField(default=False, verbose_name='Other Specify'),
        ),
        migrations.AlterField(
            model_name='grievance',
            name='reporter_phone',
            field=models.CharField(max_length=13, null=True, verbose_name='Complainant\u2019s Telephone No'),
        ),
    ]
