# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-11-02 12:12
from __future__ import unicode_literals

import django.core.validators
from django.core.management import call_command
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    def load_data(apps, schema_editor):
        call_command("loaddata", "referral_status.json")
        call_command("loaddata", "external_organisation_type.json")

    dependencies = [
        ('DreamsApp', '0029_auto_20180517_1259'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientLTFU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_followup', models.DateField(verbose_name='Date of Followup')),
                ('type_of_followup', models.CharField(choices=[(1, 'Call'), (2, 'Visit')], max_length=10, verbose_name='Type of Followup')),
                ('result_of_followup', models.CharField(max_length=255, verbose_name='Result of Followup')),
                ('comment', models.CharField(blank=True, max_length=255, null=True, verbose_name='Comment')),
            ],
            options={
                'verbose_name': 'Client LTFU',
                'verbose_name_plural': 'Client LTFUs',
            },
        ),
        migrations.CreateModel(
            name='ExitReason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Exit Reason',
                'verbose_name_plural': 'Exit Reasons',
            },
        ),
        migrations.CreateModel(
            name='ExternalOrganisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Organisation Name')),
                ('code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Organisation Code')),
                ('allow_specific', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'External Organisation',
                'verbose_name_plural': 'External Organisations',
            },
        ),
        migrations.CreateModel(
            name='ExternalOrganisationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='External Organisation Type')),
            ],
            options={
                'verbose_name': 'External Organisation Type',
                'verbose_name_plural': 'External Organisation Types',
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_organisation_other', models.CharField(blank=True, max_length=255, null=True)),
                ('referral_date', models.DateField()),
                ('referral_expiration_date', models.DateField()),
                ('comments', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Referral',
                'verbose_name_plural': 'Referrals',
            },
        ),
        migrations.CreateModel(
            name='ReferralStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Referral Code')),
                ('name', models.CharField(choices=[(1, 'Pending'), (2, 'Completed'), (3, 'Rejected'), (4, 'Expired')], default='Pending', max_length=20, verbose_name='Referral Name')),
            ],
            options={
                'verbose_name': 'Referral Status',
                'verbose_name_plural': 'Referral Statuses',
            },
        ),
        migrations.AddField(
            model_name='client',
            name='ovc_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='implementingpartner',
            name='parent_implementing_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='DreamsApp.ImplementingPartner', verbose_name='Parent Implementing Partner'),
        ),
        migrations.AlterField(
            model_name='clienttransfer',
            name='transfer_reason',
            field=models.TextField(default='Client transferred from IP', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='referral',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_referral', to='DreamsApp.Client'),
        ),
        migrations.AddField(
            model_name='referral',
            name='external_organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='DreamsApp.ExternalOrganisation'),
        ),
        migrations.AddField(
            model_name='referral',
            name='intervention_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='intervention_type', to='DreamsApp.InterventionType'),
        ),
        migrations.AddField(
            model_name='referral',
            name='receiving_ip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receiving_ip', to='DreamsApp.ImplementingPartner'),
        ),
        migrations.AddField(
            model_name='referral',
            name='referral_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referral_status', to='DreamsApp.ReferralStatus'),
        ),
        migrations.AddField(
            model_name='referral',
            name='referring_ip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referral_ip', to='DreamsApp.ImplementingPartner'),
        ),
        migrations.AddField(
            model_name='externalorganisation',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DreamsApp.ExternalOrganisationType', verbose_name='Organisation Type'),
        ),
        migrations.AddField(
            model_name='clientltfu',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_ltfu', to='DreamsApp.Client'),
        ),
        migrations.AddField(
            model_name='client',
            name='exit_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DreamsApp.ExitReason'),
        ),
        migrations.AddField(
            model_name='client',
            name='external_organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DreamsApp.ExternalOrganisation'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='external_organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='external_organisation', to='DreamsApp.ExternalOrganisation'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='referral',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referral', to='DreamsApp.Referral'),
        ),
    ]
