# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-13 01:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DreamsApp', '0030_auto_20160813_0130'),
    ]

    operations = [
        migrations.AddField(
            model_name='grievance',
            name='other_grievance_specify',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Specify Grievance'),
        ),
    ]
