# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-11-05 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DreamsApp', '0030_auto_20181102_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='rejectreason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
