# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-11-05 11:36
from __future__ import unicode_literals

from django.core.management import call_command
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    def load_data(apps, schema_editor):
        call_command("loaddata", "implementing_partner_funder.json")

    dependencies = [
        ('DreamsApp', '0031_referral_rejectreason'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImplementingPartnerFunder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Funder')),
            ],
            options={
                'verbose_name': 'Funder',
                'verbose_name_plural': 'Funders',
            },
        ),
        migrations.AddField(
            model_name='implementingpartner',
            name='implementing_partner_funder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='DreamsApp.ImplementingPartnerFunder', verbose_name='Funder'),
        ),
    ]
