# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-13 02:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DreamsApp', '0031_grievance_other_grievance_specify'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrievanceStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(verbose_name='Code')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Grievance Status',
                'verbose_name_plural': 'Grievance Status List',
            },
        ),
        migrations.RemoveField(
            model_name='grievance',
            name='is_open',
        ),
        migrations.AlterField(
            model_name='grievance',
            name='complainant_feedback_date',
            field=models.DateField(verbose_name='Date of Feedback to Complainant'),
        ),
        migrations.AddField(
            model_name='grievance',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DreamsApp.GrievanceStatus', verbose_name='Status'),
        ),
    ]
