# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-13 02:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DreamsApp', '0032_auto_20160813_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grievance',
            name='status',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='DreamsApp.GrievanceStatus', verbose_name='Status'),
        ),
    ]
