# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-11-05 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DreamsApp', '0032_auto_20181105_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referralstatus',
            name='name',
            field=models.CharField(default='Pending', max_length=20, verbose_name='Referral Name'),
        ),
    ]
