# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-13 02:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DreamsApp', '0033_auto_20160813_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grievance',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='grievance',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Modified at'),
        ),
        migrations.AlterField(
            model_name='grievance',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By'),
        ),
    ]
