# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-11-05 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DreamsApp', '0033_auto_20181105_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervention',
            name='external_organisation_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
