# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-13 03:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DreamsApp', '0034_auto_20160813_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grievance',
            name='closure_date',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Date Closed'),
        ),
        migrations.AlterField(
            model_name='grievance',
            name='complainant_feedback_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Feedback to Complainant'),
        ),
        migrations.AlterField(
            model_name='grievance',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='grievance',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Date Reported'),
        ),
        migrations.AlterField(
            model_name='grievance',
            name='modified_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Modified at'),
        ),
        migrations.AlterField(
            model_name='grievance',
            name='reporter_phone',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='Complainant\u2019s Telephone No'),
        ),
        migrations.AlterField(
            model_name='grievance',
            name='resolution_date',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Date of resolution'),
        ),
    ]
