# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-18 09:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DreamsApp', '0036_auto_20160815_0542'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientCashTransferDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_client_recepient', models.BooleanField(default=False, verbose_name='Is AGYW the Recepient?')),
                ('recipient_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Reporter Name')),
                ('recipient_relationship_with_client', models.CharField(blank=True, max_length=150, null=True, verbose_name='Relationship with AGYW')),
                ('mobile_service_provider_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Name of Mobile Service Provider')),
                ('recipient_phone_number', models.CharField(blank=True, max_length=13, null=True, verbose_name='Phone No')),
                ('bank_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Bank')),
                ('bank_branch_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Branch')),
                ('bank_account_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Account name')),
                ('bank_account_number', models.CharField(blank=True, max_length=250, null=True, verbose_name='Account number')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DreamsApp.Client', verbose_name='Dreams Beneficiary\\(AGYW\\)')),
            ],
            options={
                'verbose_name': 'Cash Transfer Detail',
                'verbose_name_plural': 'Cash Transfer Details',
            },
        ),
        migrations.CreateModel(
            name='PaymentMode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(verbose_name='Code')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Payment Mode',
                'verbose_name_plural': 'Payment Modes',
            },
        ),
        migrations.AddField(
            model_name='clientcashtransferdetails',
            name='payment_mode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DreamsApp.PaymentMode', verbose_name='Prefered Mode of receiving Cash'),
        ),
    ]
