# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-11-13 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DreamsApp', '0036_auto_20181112_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientltfutype',
            name='code',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='clientltfutype',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='referralstatus',
            name='code',
            field=models.IntegerField(verbose_name='Referral Code'),
        ),
        migrations.AlterField(
            model_name='referralstatus',
            name='name',
            field=models.CharField(default='Pending', max_length=20, verbose_name='Referral Name'),
        ),
    ]
