# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-12-05 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DreamsApp', '0037_auto_20181113_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referralstatus',
            name='code',
            field=models.IntegerField(verbose_name='Referral Code'),
        ),
        migrations.AlterField(
            model_name='referralstatus',
            name='name',
            field=models.CharField(default='Pending', max_length=20, verbose_name='Referral Name'),
        ),
    ]
