# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-19 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DreamsApp', '0038_auto_20160818_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcashtransferdetails',
            name='name_phone_number_registered_to',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Name to whom the Phone No. is registered'),
        ),
        migrations.AlterField(
            model_name='clientcashtransferdetails',
            name='is_client_recepient',
            field=models.BooleanField(default=False, verbose_name='Is the Recipient an AGYW?'),
        ),
        migrations.AlterField(
            model_name='clientcashtransferdetails',
            name='recipient_name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Name of Recipient'),
        ),
        migrations.AlterField(
            model_name='clientcashtransferdetails',
            name='recipient_relationship_with_client',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Recipient Relationship with AGYW'),
        ),
    ]
