# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-19 12:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DreamsApp', '0039_auto_20160819_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcashtransferdetails',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DreamsApp.Client', verbose_name='Dreams Beneficiary\\(AGYW\\)'),
        ),
    ]
