# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-01-16 14:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DreamsApp', '0038_auto_20181205_1646'),
        ('DreamsApp', '0039_auto_20181115_1440'),
    ]

    operations = [
    ]
