# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-01-29 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DreamsApp', '0041_auto_20190123_1401'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurableParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(blank=True, null=True, unique=True, verbose_name='Parameter Code')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Parameter Name')),
                ('value', models.CharField(max_length=255, verbose_name='Parameter Name')),
            ],
            options={
                'verbose_name': 'Configurable Parameter',
                'verbose_name_plural': 'Configurable Parameters',
            },
        ),
    ]
