# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-01-25 12:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DreamsApp', '0041_auto_20190123_1401'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientFollowUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_followup', models.DateField(verbose_name='Date of Followup')),
                ('result_of_followup', models.CharField(max_length=255, verbose_name='Result of Followup')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_follow_up', to='DreamsApp.Client')),
            ],
        ),
        migrations.RenameModel(
            old_name='ClientLTFUType',
            new_name='ClientFollowUpType',
        ),
        migrations.AlterModelOptions(
            name='clientfollowuptype',
            options={'verbose_name': 'Follow Up Type', 'verbose_name_plural': 'Follow Up Types'},
        ),
        migrations.AlterModelOptions(
            name='clientltfu',
            options={'verbose_name': 'Client Follow Up', 'verbose_name_plural': 'Client Follow Ups'},
        ),
        migrations.AddField(
            model_name='clientfollowup',
            name='type_of_followup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_up_type', to='DreamsApp.ClientFollowUpType'),
        ),
    ]
