# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-01-22 06:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DreamsApp', '0041_auto_20190116_1455'),
        ('DreamsApp', '0040_merge_20181214_1323'),
    ]

    operations = [
    ]
