# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-11-05 14:54
from __future__ import unicode_literals

from django.core.management import call_command
from django.db import migrations, models


class Migration(migrations.Migration):
    def load_data(apps, schema_editor):
        call_command("loaddata", "client_followup_type.json")

    dependencies = [
        ('DreamsApp', '0042_auto_20190201_1039'),
    ]
