# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-01-27 19:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DreamsApp', '0043_auto_20190127_2233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientltfu',
            name='client',
        ),
        migrations.RemoveField(
            model_name='clientltfu',
            name='result_of_followup',
        ),
        migrations.RemoveField(
            model_name='clientltfu',
            name='type_of_followup',
        ),
        migrations.DeleteModel(
            name='ClientLTFU',
        ),
    ]
