# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-01-29 12:13
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DreamsApp', '0043_add_configurableparameter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='age_at_enrollment',
            field=models.IntegerField(blank=True, default=9, null=True, verbose_name='Age at Enrollment'),
        ),
        migrations.AlterField(
            model_name='interventiontypepackage',
            name='lower_age_limit',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(9), django.core.validators.MaxValueValidator(24)], verbose_name='Lower age limit'),
        ),
        migrations.AlterField(
            model_name='interventiontypepackage',
            name='upper_age_limit',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(9), django.core.validators.MaxValueValidator(24)], verbose_name='Upper age limit'),
        ),
        migrations.AlterField(
            model_name='servicepackage',
            name='lower_age_limit',
            field=models.PositiveIntegerField(default=9, validators=[django.core.validators.MinValueValidator(9), django.core.validators.MaxValueValidator(24)], verbose_name='Lower age limit'),
        ),
        migrations.AlterField(
            model_name='servicepackage',
            name='upper_age_limit',
            field=models.PositiveIntegerField(default=24, validators=[django.core.validators.MinValueValidator(9), django.core.validators.MaxValueValidator(24)], verbose_name='Upper age limit'),
        ),
    ]
