# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-11-30 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DreamsApp', '0049_intervention_odk_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervention',
            name='odk_uuid',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, unique=True),
        ),
    ]
