# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2021-02-03 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DreamsApp', '0050_auto_20201130_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='guardian_national_id',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='National ID (Care giver/Guardian)'),
        ),
    ]
