# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2021-02-24 04:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DreamsApp', '0051_auto_20210203_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='dreams_id',
            field=models.CharField(blank=True, db_index=True, max_length=250, null=True, verbose_name='DREAMS ID'),
        ),
        migrations.AlterField(
            model_name='client',
            name='dss_id_number',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='DSS ID Number'),
        ),
        migrations.AlterField(
            model_name='client',
            name='first_name',
            field=models.CharField(blank=True, db_index=True, max_length=250, null=True, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='client',
            name='guardian_phone_number',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Phone Number(Care giver/Guardian)'),
        ),
        migrations.AlterField(
            model_name='client',
            name='last_name',
            field=models.CharField(blank=True, db_index=True, max_length=250, null=True, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='client',
            name='middle_name',
            field=models.CharField(blank=True, db_index=True, max_length=250, null=True, verbose_name='Middle Name'),
        ),
        migrations.AlterField(
            model_name='client',
            name='odk_enrollment_uuid',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='ovc_id',
            field=models.CharField(blank=True, db_index=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='client',
            name='reason_exited',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='reason_voided',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='relationship_with_guardian',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Relationship with Guardian'),
        ),
        migrations.AlterField(
            model_name='client',
            name='verification_doc_no',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Verification Doc No'),
        ),
        migrations.AlterField(
            model_name='client',
            name='verification_document_other',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Verification Document(Other)'),
        ),
    ]
