# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2021-03-01 04:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DreamsApp', '0052_servicedelegation'),
        ('DreamsApp', '0052_auto_20210224_0717'),
    ]

    operations = [
    ]
