# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2021-03-04 03:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('DreamsApp', '0052_auto_20210224_0717'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceDelegation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Delegation start date')),
                ('end_date', models.DateField(verbose_name='Delegation end date')),
                ('financial_year', models.CharField(max_length=250, verbose_name='Financial year')),
                ('date_created', models.DateField()),
                ('date_updated', models.DateField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_delegation_date_created', to=settings.AUTH_USER_MODEL)),
                ('delegated_implementing_partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegated_implementing_partner', to='DreamsApp.ImplementingPartner')),
                ('intervention_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegation_intervention_type', to='DreamsApp.InterventionType')),
                ('main_implementing_partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_implementing_partner', to='DreamsApp.ImplementingPartner')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_delegation_date_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
