# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2021-06-11 03:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DreamsApp', '0053_servicedelegation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicedelegation',
            name='financial_year',
        ),
        migrations.AlterUniqueTogether(
            name='servicedelegation',
            unique_together=set([('main_implementing_partner', 'delegated_implementing_partner', 'start_date', 'end_date', 'intervention_type')]),
        ),
    ]
