# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2021-06-16 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DreamsApp', '0054_auto_20210611_0618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicedelegation',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='servicedelegation',
            name='date_updated',
            field=models.DateField(auto_now=True),
        ),
    ]
