
# Transfer constants
TRANSFER_INITIATED_STATUS = 1
TRANSFER_ACCEPTED_STATUS = 2
TRANSFER_REJECTED_STATUS = 3

# Enrolment constants
MINIMUM_ENROLMENT_AGE = 9
MAXIMUM_ENROLMENT_AGE = 24

# Referral constants
REFERRAL_PENDING_STATUS = 1
REFERRAL_COMPLETED_STATUS = 2
REFERRAL_REJECTED_STATUS = 3
REFERRAL_EXPIRED_STATUS = 4